const String duong_doi_1 =
    "Năng lượng và ý nghĩa của Con số Đường đời 1. \nBạn là một nhà lãnh đạo bẩm sinh, có nhiều suy nghĩ, phát minh, ý tưởng và tầm nhìn độc đạo. Mặc dù rất thành thạo trong việc bắt đầu mọi thứ , bạn không phải là người xuất xắc trong việc nhìn nhận tổng thể, từ đầu đến cuối. Những chi tiết tẻ nhạt có thể khiến bạn mất hứng thú. Trong cách nối quan hệ, điều quan trọng là bạn phải giữ được sự độc lập của mình, nhưng bạn cũng muốn bản thân là là một phần quan trọng và cần thiết. Bạn thích chịu trách nhiệm. Tuy nhiên, bạn phải nỗ lực để tránh trở nên độc đoán và ích kỷ. Bạn có khả năng và tự tin; tuy nhiên, bạn cũng khó khăn vì tự kỷ ám thị. Hãy nhớ đừng quá khắt khe với chính mình, nếu không chính điều này có thể cản trở khả năng tiến bộ và đạt được mục tiêu của bạn. Điều vô cùng quan trọng là bạn phải nỗ lực để phát triển ý thức cá nhân để chính bạn có thể rút ra các bài học và chủ động cải thiện cuộc sống và các mối quan hệ của mình. Khi nói đến sự nghiệp, nhiều người có Con số Đường đời 1 là doanh nhân hoặc ông chủ, họ không thích bị chỉ bảo phải làm gì. Bạn có tính cạnh tranh gay gắt, điều này giúp bạn vươn lên dẫn đầu. Nhiều  vận động viên chuyên nghiệp  thành công và vận động viên Olympic cũng có Con số đường đời này. Nếu không được giải tỏa, năng lượng cạnh tranh trong bạn có thể trở nên quyết liệt và hủy diệt. bạn phải học cách giữ bình tĩnh. Sự hài lòng tức thì và kết quả trước mắt là thứ thúc đẩy bạn , điều này có thể khiến bạn bốc đồng và thiếu quan tâm đến người khác. Những người có Con số Đường đời  1 thường gặp các vấn đề về sức khỏe liên quan đến hệ tiêu hóa. Họ cũng có thể bị chứng đau nửa đầu, nghiện ngập và cách tình trạng liên quan đến căng thẳng như đau vai và lưng. Đường thẳng tạo thành số 1 đại diện cho ranh giới bạn cần dựng lên . Nó cũng cho thấy cách số 1 đứng một mình: một cá nhân duy nhất phấn đấu cho vị trí hàng đầu.\nNhững người nổi tiếng có Con số Đường đời 1 là Justin Bieber, Tom Cruise, Lady Gaga, David Letterman, Jack Nicholson và Tiger Woods.";
const String duong_doi_2 =
    "Năng lượng và ý nghĩa của Con số Đường đời 2. Tốt bụng , ngoại giao tốt và có tinh thần hợp tác đều là những đặc điểm nổi bật của Con số Đường đời 2. Bạn là người kiên nhẫn nhất trong tất cả con số và cực kỳ hạt cảm, nhạy bén và giàu cảm xúc. Cảm xúc của bạn có thể chuyển từ khóc sang cười. Cùng với sự nhạy cảm đó là những khả năng về trực giác, bạn có khả năng bẩm sinh. Mức độ nhạy cảm của Con số Đường đời này mở rộng đối với tất cả các loại chất gây dị ứng, bao gồm thực phẩm, sản phẩm chăm sóc da và tóc, bụi, hóa chất, dược phẩm và nhiều loại khác. Các vấn đề về sức khỏe khác có thể gồm lo lắng thái quá, trầm cảm và cách vấn đề về dạ dày.\nSố 2 có dáng cong và cho thấy sự thỏa hiệp, vì vậy bạn cần phải học cách đứng lên bảo vệ chính mình.\nNhững nhân vật nổi tiếng  có Con số Đường đời 2 là Kathy Bates, Angela Bassett, Tony Bennett, Mariah Carey, Jennifer Lopez và Vera Wang.";

const String duong_doi_3 =
    "Năng lượng và ý nghĩa của Con số Đường đời 3\nCon số Đường đời 3 thích nổi bật! Bạn sống 'cuộc sống của những bữa tiệc', được yêu thích và quảng giao. Năng lượng của bạn thúc đẩy sự mở rộng. (Nếu bạn kể một câu chuyện cho những người có Con số Đường đời 3, họ sẽ cải biên câu chuyện khi kể lại cho người khác, sử dụng các từ ngữ hoa mỹ, nhấn nhá và chắc chắn là thêm một số chi tiết cường điệu). Sự lạc quan và nhiệt tình của bạn có khả năng lan truyền. Bạn cần giải tỏa năng lượng sáng tạo của mình, nếu không nó sẽ bùng nổ dưới dạng cảm xúc.\nCảm xúc của bạn có thể dễ dàng bị tổn thương đặc biệt là bằng lời nói. Điều này thật trớ trêu, vì bản thân bạn cũng có cái lưỡi sắc bén và hiếm khi gặp khó khăn trong việc thể hiện bản thân. Trên thực tế, bạn phải cẩn trọng để xem mình có đang hỗn xược, hoài nghi hoặc ủ rũ không. Hãy nhớ rằng lời nói của bạn có thể làm tổn thương người khác, vì vậy hãy cẩn thận khi sử dụng chúng. Bạn có thể rất khắt khe với bản thân và có tâm lý tự ti. Bạn sử dụng năng khiếu hài hước của mình để che giấu cảm xúc bị tổn thương và sự bất an, những cách đối phó này có thể bị nhân ra dễ dàng hơn bạn nghĩ.\nNhìn chung, bạn cần thêm hành động chủ động vào những mối quan hệ thân thiết nhất của mình để mọi người xung quanh cảm thấy họ được trân trọng.\nTài năng nghề nghiệp của con số Đường đời này là sự sáng tạo. Nhạc sĩ, diễn viên , nghệ sĩ vũ công, nhà văn và đầu bếp là một vài lựa chọn nghề nghiệp nổi trội để bạn cân nhắc. Ở mức độ rung động thấp, bạn có thể thoái thác trách nhiệm, sống vô tổ chức và chìm đắm trong tâm lý nạn nhân, phẫn nộ với bất kỳ ai tranh giành sự chú ý với bạn. Khi nỗ lực hết mình và thể hiện sự tích cực, bạn có thể trở thành nguồn động lực truyền cảm hứng, nâng cao tinh thần và mang lại niềm vui cho những người xung quanh.\nVề sức khỏe, bạn có khả năng tăng và giảm cân nhanh chóng, đôi khi ở mức báo động. Hầu hết những người có Con số Đường đời 3 đều được ban cho vẻ ngoài ưa nhìn và nũ cười đẹp. Cân nặng luôn dao động, trạng thái tinh thần và các vấn đề về họng là những vấn đề sức khỏe mà bạn cần chú ý\nSố 3 có hình dáng giống như một cặp móng ngựa nằm ngang và được coi là con số may mắn nhất. Đừng bao giờ coi vận may của bạn là điều hiển nhiên!\nNhững người nổi tiếng có Con số Đường đời 3 bao gồm Christina Aguilera, Alec Baldwin, David Bowie, Thành Long,  Katie Couric, Cameron Diaz, Joan Rivers, và Reese Witherspoon.";
const String duong_doi_4 =
    "Năng lượng và ý nghĩa của Con số Đường đời 4\nBạn là một người lập kế hoạch thực chiến, luôn đọc các hướng dẫn cẩn thận và chuẩn bị sẵn sàng trong mọi tình huống. Bạn là người người đáng tin cậy, tận tâm và hành động nhanh chóng. Những điều bất ngờ và thay đổi là kryptonite của bạn. Bạn mong muốn kiểm soát kết quả, vì vậy bạn cần học cách quản lý và đón nhận sự thay đổi cũng như tin tưởng vào những sức mạnh vô hình của cuộc sống. Là người bi quan trong lòng, ngay cả vào một ngày trời đẹp, bạn vẫn nhìn ra những đám mây ở phía xa và mang theo ô đi làm.\nNhững ranh giới kiên cố bảo vệ bạn, nhưng điều quan trọng là phải học cách linh hoạt và chấp nhận sự giúp đỡ của người khác. Tính cách thực tế của bạn luôn không cho phép bạn đối xử tốt với bản thân, phung phí hoặc trải nghiệm khía cạnh xa hoa của cuộc sống.\nBất chấp tính kỷ luật, sự trì hoãn có thể là vấn đề đối với bạn, đặc biệt nếu bạn là người Nợ Nghiệp 13/4. Ngược lại, những người có Con số Đường đời 4 khá kỷ luật cà muốn kiểm soát mọi thứ và mọi người. Ở rung độ thấp, bạn có thể rất tính toán và thích thao túng. Hãy chắc chắn rằng bạn luôn kiểm soát được cái tôi của mình.\nBạn là người thân thiện một cách tự nhiên, nhưng có xu hướng không để người khác đến quá gần. Điều quan trọng là phải thể hiện mặt yếu đuối của bản thân để phát triển  các mối quan hệ thân thiết. Khi trung thực là tính cách mặc định của bạn, người khác sẽ biết bạn là người đáng tin cậy.\nNhững người có Con số Đường đời này có xu hướng tìm kiếm thành công trong các lĩnh vực như giáo dục, kinh doanh, chăm sóc sức khỏe, quản trị, xây dựng, chính trị và kế toán. Họ là những người xây dựng, kiến tạo. Một nền tảng vững chắc và một khoản tiết kiệm là tất cả những gì bạn cần để cảm thấy an tâm và hạnh phúc.\nVấn đề sức khỏe thường gặp cho nhóm người này là cách bệnh liên quan đến căng thẳng, như đau khớp, đau nửa đầu, đau bụng , cách vấn đề về lưng, ám ảnh cưỡng chế và chứng rối loạn lo âu.\nSố 4 được tạo thành hoàn toàn từ các đường thẳng, thể hiện nhu cầu duy trì trật tự và hiệu quả, Hãy nhớ luôn duy trì sự linh hoạt.\nNhững người nổi tiếng có Con số Đường đời 4 là  Kate Hudson, Will Smith, Chris Tucker, Bill Gates và Usher.";
const String duong_doi_5 =
    "Năng lượng và ý nghĩa của Con số Đường đời 5 \nThắt dây an toàn vào nào! Cuộc sống của người có Con số Đường đời 5 là một chuyến đi thú vị và không thể đoán trước. Bốc đồng và luôn sẵn sàng cho bất cứ điều gì, bạn thích phiêu lưu, tự do và du lịch. Các quy tắc chỉ có tính định hướng với bạn và bạn có xu hướng bẻ cong và bất chấp chúng theo ý muốn của mình. Sự buồn chán có thể dẫn bạn đến chủ nghĩa thoát ly, điều này có thể nhanh chóng chuyển sang trạng thái tự hủy hoại bản thân. Nếu mang Nợ Nghiệp 14/5, bạn sẽ phải vật lộn với nhiều cám dỗ khác nhau, cả từ chính bản thân và những người yêu thương. Bạn tiêu tiền cho những chuyến du lịch và trải nghiệm hơn là những thứ vật chất. Bạn có thể là nguồn cơn lo lắng của gia đình.\nKhi nói đến các mối quan hệ, bạn có thể hơi khó kìm nén và gặp khó khăn để giữ cam kết. Bạn là người gợi cảm và đòi hỏi sự đa dạng và kích thích liên tục. Bạn có khả năng cam kết và bạn. Bạn nên tránh kết hôn khi còn trẻ, vì có thể đó sẽ là cuộc hôn nhân thất bại.\nNhững người có Con số Đường đời 5 thường đa tài và bạn sẽ thành công trong hầu hết mọi thứ mà bạn quan tâm. Bạn có quan điểm tiến bộ và là người đầu tiên đón nhận những ý tưởng mới. Bạn dễ dàng thích nghi, vì vậy công nghệ có thể là một lựa chọn nghề nghiệp tuyệt vời. Bạn là người kể chuyện tự nhiên và xuất sắc trong việc thúc đẩy và truyền cảm hứng cho người khác. Bạn hoàn toàn có thể bán bất cứ thứ gì với sự quyến rũ và đáng yêu của mình. Những đặc điểm này có thể đưa bạn đến với sự nghiệp quảng cáo, tiếp thị, làm việc mặc đồng phục, chẳng hạn như lực lượng an ninh, người thực thi pháp luật, phi công hoặc tiếp viên hàng không. Nhiều người cũng có lòng hiếu khách. và cũng luôn có các công việc tự do để bạn hay đặt câu hỏi về việc bạn nghỉ ngơi!\nBạn cũng có năng khiếu bẩm sinh về ngôn ngữ.\nỞ mức độ rung động thấp, bạn có xu hướng nhận về mình ý tưởng hoặc công việc không phải của bạn. Điều này có thể gây tổn hại đến danh tiếng của bạn và khiến mọi người phật lòng. Bài học của bạn nằm ở sự chăm chỉ, kiên trì và thể hiện sử ghi nhận khi cần thiết.\nNgười có Con số Đường đời 5 dễ gặp các vấn đề về cảm xúc, nghiện ngập, suy kiệt tuyến thượng thận và đau khớp. Hãy nhớ uống đủ nước để tránh mất nước.\nHình dạng của số 5 mở ra ở cả bên phải và bên trái, thẳng ở trên và cong ở dưới. Điều này cho thấy nhu cầu về sự đa dạng và thay đổi liên tục. Hãy nhớ giữ bình tĩnh và kiên định.\nNhững người nổi tiếng có Con số Đường đời 5 có thể kể đến như Ellen DeGeneres, Mick Jagger, Angelina Jolie, Willie Nelson, Sean Penn, Keith Richards và Tina Turner.";
const String duong_doi_6 =
    "Năng lượng và ý nghĩa của Con số Đường đời 6 Rung động của con số 6 là về TÌNH YÊU! Quyến rũ và lôi cuốn, với tính cách thu hút, bạn có khả năng hấp dẫn mọi người đến bất kỳ công việc nào bạn làm. \nNhờ sự hào phóng, tốt bụng và hấp dẫn, bạn được ngưỡng mộ và thậm chí được yêu mến (điều này có thể khiến bạn bối rối). \nBạn là người yêu thích tụ tập mọi người và cũng là người yêu động vật.\nBạn giúp đỡ mọi người mà không đơn giản là bày tỏ sự thông cảm. \nTính cách của bạn khá cực đoan. \nNgười có Con số Đường đời 6 có phẩm chất ma quỷ hoặc thiên thần. \nBạn là một cá nhân giàu lòng nhân ái và là một người bạn tuyệt vời, trung thành đến cung.\nThật không may, lòng trung thành đó không phải lúc nào cũng được đáp lại. \nMột trong những bài học của bạn sẽ là hiểu và trải nghiệm ý nghĩa thực sự của phản bội, đôi khi có thể là trải nghiệm đau đớn. \nBạn có xu hướng thu hút những người bị tổn thương, và bạn cần cảm giác bản thân là người có ích. \nTrong các mối quan hệ, Bạn phải học cách cân bằng giữa giúp đỡ và can thiệp. \nNgười có Con số đường đời 6 thường thanh công trong lĩnh vực giảng dạy, khách sạn, tâm lý học, quản lý, bất động sản, chính phủ các ngành nghề liên quan đến động vật hoặc lĩnh vực thẩm mỹ như thời trang hay thiết kế nội thất. \nBạn hiểu những thứ xa hoa trong cuộc sống hơn bất kỳ ai khác. \nQuan điểm cứng rắn của bạn cũng sẽ khiến bạn gặp rắc rối. Nếu thấy mình luôn trong tình trạng căng thẳng về tài chính, bạn đang không sống đúng với mục đích của mình. \nNhững người số 6 yêu nhiều, đôi khi yêu quá nhiều, vì họ cũng có xu hướng cất giấu tình cảm trong lòng. \nCác vấn đề về sức khỏe thường gặp liên quan đến khả năng sinh sản và tim mạch. \nHình dạng của số 6 giống như một phụ nữ mang thai. \nMột điều không bao giờ thay đổi đối với số 6: tầm quan trọng của gia đình. \nCác bậc cha mẹ có Con số Đường đời này cảm thấy khó khăn khi nhìn thấy con cái lớn lên, trưởng thành, độc lập và phải kháng cự lại thôi thúc can thiệp. \nCho dù bạn có quyết định lập gia đình hay không , bạn vẫn luôn có những hành động tuyệt vời để chăm sóc người khác. \nNhững người nổi tiếng có Con số Đường đời 6 gồm: Victoria Beckham, Bill Maher, Michael Jackson, Stephen King, John Lennon, Richard Nixon, Rosie O'Donnell và  Bruce Willis.";
const String duong_doi_7 =
    "Bạn là người thông minh và bí ẩn, thuộc típ người mạnh mẽ và trầm lặng. Bạn thích phân tích, tự nghiên cứu và không bao giờ nhìn nhận mọi thứ qua bề nổi. Nếu ai đó có bí mật, bạn sẽ tìm thấy nó. \nBản chất bạn là người đa nghi và tò mò. Bạn bẩm sinh có trực giác nhạy bén; tâm linh và siêu hình học là những bí ẩn thu hút bạn. Điều quan trọng đối với bạn, với tư cách là người có con số đường đời 7, là phải có niềm tin tâm linh hoặc tôn giáo. Nếu không, cuộc sống của bạn có thể sẽ thiếu mục đích. Các yếu tố có tính chất lịch sử hoặc những câu chuyện xa xưa đều khiến bạn thích thú. Số 7 cũng thích tích trữ thông tin, thường có cả giá sách chưa đọc.\nKiến thức và sự nhanh trí của bạn mang lại cho bạn khiếu hài hước độc đáo và giúp bạn trở nên thu hút và đáng ngưỡng mộ. , vì dường như bạn đang kìm hãm và giữ bí mật. Hãy thẳng thắn và trung thực trong giao tiếp. (Điều này đặc biệt đúng nếu bạn mang Nợ Nghiệp 16/7.) Ở độ rung động thấp, các bài học khác sẽ bao gồm sự ghen tị khi yêu cũng như các vấn đề về cái tôi. Tuy nhiên, bạn lại gặp khó khăn trong việc duy trì các mối quan hệ thân thiết, vì dường như bạn đang kìm hãm và giữ bí mật. Hãy thẳng thắn và trung thực trong giao tiếp. (Điều này đặc biệt đúng nếu bạn mang Nợ Nghiệp 16/7.) Ở độ rung động thấp, các bài học khác sẽ bao gồm sự ghen tị khi yêu cũng như các vấn đề về cái tôi. Bạn sẽ học cách duy trì và tôn trọng các ranh giới và quyền riêng tư của người khác cũng như những gì có thể vi phạm ranh giới của chính bạn.\nỞ độ rung động cao, bạn sở hữu từ tính bí ẩn. Bạn quyến rũ, thông minh, hài hước và hấp dẫn. Bạn thích làm cho người khác cảm thấy thoải mái, mặc dù trong tâm trí bạn vẫn có những phán xét hay đánh giá riêng. Những người sở hữu số 7 mà không có người số 3 ở gần để cân bằng có thể trở nên ẩn dật và chống đối xã hội.\nNhững người có Con số Đường đời 7 sẽ thành công ở các lĩnh vực nghề nghiệp như nghiên cứu, sử học, người quản lý bảo tàng, lập hồ sơ tội phạm, giáo viên thần học hoặc tôn giáo hay luật sư. Bạn thích làm việc một mình. Số 7 thường sẽ chỉ làm việc cho một số công ty hoặc tổ chức trong sự nghiệp của mình.\nBạn thường bị khó ngủ. Bạn cũng có thể gặp các vấn đề về cổ vì là người luôn bận rộn. Thiền, yoga, tắm hoặc đi bộ đường dài có thể giúp bạn tĩnh tâm và thư giãn.\nHình dạng của số 7 giống như một boomerang phản ánh chính nó trong các mối quan hệ, hoàn cảnh sống và sự nghiệp. Bạn thường thấy mình quay trở lại với những người, công việc và địa điểm giống nhau. Chân của số 7 không có điểm tựa. Việc mất cân bằng có thể dẫn đến trầm cảm, nghiện ngập và mất ngủ.\nNhững người nổi tiếng có Con số Đường đời 7 gồm Muhammad Ali, Christian Bale, Robert Blake, Mel Gibson, Kelsey Grammer, Al Pacino, Jerry Seinfeld, Danielle Steel và James Woods.";
const String duong_doi_8 =
    "Sinh ra để trở thành ông chủ, nếu không phải là người chịu trách nhiệm, bạn sẽ giả vờ hay tỏ ra như vậy. Bạn là người có tầm nhìn xa và cũng khá liều lĩnh. Hãy nhớ rằng có một ranh giới giữa quyền lực và tham nhũng, và bạn phải bước đi trên ranh giới đó một cách cẩn thận. Bạn thích tiền và tiêu xài hoang phí. Những việc bạn làm liên quan đến tiền sẽ phản tác dụng nếu bạn làm vì mục đích sai trái. Tuy nhiên, bạn có thể đạt được thành công nếu làm việc với sự chính trực và thành thật. Bạn phải nhớ rằng phần thưởng không phải lúc nào cũng xuất hiện dưới dạng tiền bạc, chúng cũng có thể là sự công nhận và di sản. Số 8 trải qua nhiều thăng trầm trong cuộc sống.\nViệc thể hiện tình yêu và tình cảm là điều khó khăn đối với bạn. Hãy ngừng cố chấp và kiểm soát. Cuộc sống của bạn có thể là cánh cửa xoay tròn của các mối quan hệ và tình bạn. Ở độ rung động thấp, bạn có thể gặp khó khăn trong việc trung thành và giữ bí mật và có thể bị coi là đạo đức giả. Cái tôi, sự kiêu ngạo và ích kỷ có thể là điểm yếu của bạn. Bạn dễ nổi giận nhưng con giận luôn nhanh chóng qua đi. Bạn học hỏi những kinh nghiệm này. Hãy học cách chịu trách nhiệm, thành thật xin lỗi và tiến bộ.\nSố 8 thường trải qua nhiều công việc tại các công ty khác nhau, cố gắng tìm ra môi trường phù hợp. Với Con số Đường đời 8, bạn sẽ hoàn thành xuất sắc mọi công việc trong môi trường kinh doanh và đây cũng là lĩnh vực bạn có lợi thế và tạo được sự ảnh hưởng, như ngân hàng. bất động sản, tài chính và báo chí. Bạn giỏi công tác tổ chức, huấn luyện, giám sát và chỉ đạo. Bạn được thúc đẩy bởi tiền bạc, quyền lực và sự công nhận. Hãy luyện tập và cải thiện sự khéo léo của bạn để ý tưởng của bạn được tiếp nhận tốt hơn.\nNhững thách thức về sức khỏe với số 8 là các vấn đề liên quan đến căng thẳng như huyết áp cao và các vấn đề về tim mạch.\nHình dạng của số 8 được tạo thành từ hai vòng tròn dính liền thể hiện tinh thần và vật chất. Bạn phải luôn giữ cho hai mặt này cân bằng. Nếu không có sự cân bằng, số 8 sẽ không bao giờ tìm thấy sự hài lòng thực sự. Hình dạng đối xứng này cũng có nghĩa là bạn có thể đảo ngược hoàn toàn và toàn bộ bất cứ lúc nào.\nNhững người nổi tiếng có Con số Đường đời 8 göm Giorgio Armani, Cindy Crawford, Jane Fonda, Aretha Franklin, Richard Gere, Barbra Streisand, Martin Scorsese và Elizabeth Taylor.";
const String duong_doi_9 =
    "Những người sở hữu Con số Đường đời 9 có năng lượng của một tâm hồn hoài cổ. Nhiều kiếp trước mang lại cho bạn sự khôn ngoan trong tiềm thức. Bạn có khiếu hài hước, thông minh và dí dỏm. Bạn lan truyền tiếng cười đến mọi người. Số 9 cũng có trực giác tuyệt vời. Bạn là người không bốc đồng và thường suy nghĩ xa xôi.\nLuận điểm bạn đưa ra rất khó để tranh luận (mặc dù đôi khi điều này sẽ rất mệt mỏi nếu bạn là người sai). Là một học sinh giỏi với khả năng đọc nhanh, bạn tiếp thu thông tin như một miếng bọt biển và duy trì việc học trong suốt cuộc đời.\nBạn quyến rũ, hấp dẫn, lãng mạn và không gặp khó khăn khi thu hút bạn đời. Tuy nhiên, thật khó để tìm được một người có trí tuệ như bạn hoặc người có thể chia sẻ khiếu hài hước và thực sự khiến bạn cười.\nỞ độ rung động thấp, bạn có thể hạ mình. Bạn có xu hướng giải thích quá mức mọi thứ, cho rằng người khác không thể hiểu được. Bạn cũng có thể là kẻ thù tồi tệ nhất của chính mình, tự hủy hoại bản thân ngay khi đang ở trên bờ vực thành công.\nTrong sự nghiệp, bạn mong muốn giúp đỡ mọi người. Bạn có thể tìm thấy sự thỏa mãn bằng cách truyền cảm hứng cho người khác bằng ý tưởng của mình với tư cách là một nhà văn, nghệ sĩ hoặc nhà làm phim. Các ngành nghề giảng dạy, tư vấn, chăm sóc sức khỏe, kinh doanh quốc tế cũng là những lựa chọn tốt cho bạn. Bạn cũng là một nhà nhân đạo và từ thiện bẩm sinh, người không tìm kiếm sự khen ngợi hay công nhận cho những việc làm tốt của mình. Bạn thông minh đến mức nếu bạn tận dụng sự khôn ngoan của mình để phạm tội, bạn cũng có thể thành công, mặc dù cuối cùng bạn sẽ phải trả giá (nếu không ở kiếp này thì là kiếp sau).\nBạn có xu hướng không thể hiện hoặc đối phó với cảm xúc trên tinh thần xây dựng. Cảm xúc này tích tụ và dẫn đến chứng đau cổ và vai, đặc biệt là hồng. Bạn phải luôn rèn luyện thể chất. Một mối quan tâm sức khỏe khác là tình trạng tự miễn dịch của cơ thể.\nHình dạng của số 9 là một cái đầu đầy trí tuệ. Bạn có thể thấy rằng những người lạ đến với bạn để tìm kiếm thông tin ngẫu nhiên, lời khuyên hoặc chỉ đường.\nNhững người nổi tiếng có Con số Đường đời 9 gồm Cher, Gandhi, Jack Canfield, Morgan Freeman, Harrison Ford, Shirley MacLaine, Elvis Presley và Mẹ Teresa.";
const String duong_doi_11 =
    "Con số Vua 11 có trực giác nhạy bén. Bạn có thể đi trước thời đại và thế giới có thể chưa sẵn sàng cho những gì bạn phải đem đến. Do đó, nhóm 11 thưởng không ngay lập tức gặt hải được thành quả từ sự cần mẫn tiên phong của mình.\nNhờ tinh thần tiên phong, người có Con số Vua 11/2 trở thành những diễn giả truyền cảm hứng tuyệt vời, những nhà lãnh đạo tinh thần, người dẫn chương trình truyền hình, nhà thiết kế hoặc nhân vật truyền thông.\nNgười thuộc nhóm này thích ở trong một mối quan hệ, đặc biệt là một mối quan hệ bình yên, hài hòa. Họ đem cảm giác nhẹ nhàng và những đặc điểm tính cách của mình vào các mối quan hệ.\nBởi vì 11/2 cảm nhận mọi thứ quá sâu sắc nên có thể dẫn đến trầm cảm, lo lắng và tình trạng đi ứng nghiêm trọng. Sự rung cảm độc đáo của số 11 kéo theo các vấn đề sức khỏe của cả số 1 và 2.\nNhững người có Con số Đường đời 11/2 nổi tiếng gồm Jennifer Aniston, Coco Chanel, Bill Clinton, Harry Houdini, Thái tử Charles và Hoàng tử William, Barack và Michelle Obama, Ronald Reagan và Tony Robbins.";
const String duong_doi_22 =
    "22/4 được gọi là người kiến tạo đại tài. Con số Vua 22 là những người có khả năng đặc biệt, biến tầm nhìn thành hiện thực. Việc xây dựng đế chế và để lại di sản là điều vô cùng quan trọng đối với họ.\nBởi vì 22 mang năng lượng gấp đôi của số 2, người thuộc nhóm này thường sống trong căng thẳng, lo lắng và phải học cách tham gia vào các kế hoạch có tầm nhìn xa. Người 22/4 sẽ phải chịu thử thách về đạo đức và trách nhiệm. Nguồn gốc gia đình của họ có xu hướng phức tạp.\nSố 22 sẽ tìm kiếm một người bạn đời có thành tích cao để tạo cho họ cảm giác an toàn. Họ bị thu hút bởi những người có quan điểm thực tế và tập trung vào mục tiêu.\nHọc cách tin tưởng vào người khác, thay vì cố gắng kiểm soát hoặc thao túng họ là bài học cho nhóm người này. Chia sẻ tầm nhìn của bạn và để mọi người tham gia góp ý. Bạn cần những điều này nhiều hơn bạn nghĩ đấy.\nSố 22 là người cực đoan và có thể sử dụng sức mạnh của mình cho cả điều thiện hoặc ác. Phần thưởng lớn nhất của bạn sẽ đến từ những nỗ lực làm việc thiện và có mục đích tốt.\nHọ là nhóm người thích đặt tên mình lên tất cả mọi thứ và ở đây tôi không chỉ nói về việc đánh dấu chữ cái đầu tiên trong tên lên mọi vật.\nSự rung cảm độc đáo của số 22 kéo theo các vấn đề sức khỏe của cả số 2 và số 4 như dị ứng và căng thẳng.\nNhững người nổi tiếng trong nhóm người sở hữu Con số Vua 22/4 gồm Sir Richard Branson, Tina Fey, Chris Hemsworth, Dalai Lama thứ 14, Sir Paul McCartney, và Caroline Myss.";
const String duong_doi_33 =
    "Những người có Con số Vua 33/6 được biết đến là những nhà giáo đại tài. Họ là những người có sức ảnh hưởng và cảm thông lớn nhất trong các Con số Vua.\nNằm trong nhóm 33/6, bạn là người hiểu biết và nghiên cứu kỹ lưỡng tất cả các ý tưởng của mình trước khi chia sẻ chúng. Khi đạt đến tiềm năng cao nhất, bạn có khả năng giao tiếp, truyền đạt rõ ràng mà không cần chuẩn bị chương trình cụ thể, và bạn thực sự quan tâm đến nhân loại.\nĐể có kết quả 33/6 đúng phép tính phải bao gồm Con số Vua 11 hoặc 22. (Nếu không, khi Con số Đường đời của bạn là 33, bạn phải rút gọn xuống một chữ số là 6 và khi đó không phải là một Con số Vua.)\nTrong một mối quan hệ, bạn cần tập trung vào việc làm chủ cảm xúc của mình. Vì có sức hút và sự hấp dẫn nên bạn không bao giờ gặp khó khăn trong việc tìm kiếm đối tác. Tuy nhiên, hãy cẩn thận với những tính cách phức tạp, đó là sự thiếu thốn nhưng không sẵn lòng giúp đỡ chính mình.\nNhóm này thích giúp đỡ và chữa lành cho mọi người. Cảm giác thỏa mãn đến từ việc giúp đỡ người khác và chia sẻ sự khôn ngoan và năng khiếu nghệ thuật với thế giới. Bạn phù hợp với những nghề nghiệp như hỗ trợ nhân quyền, giáo dục, chăm sóc sức khỏe và nghệ sĩ thuộc mọi phương diện. Hãy tự chăm sóc bản thân.\nSự rung cảm độc đáo của số 33 kéo theo các vấn đề sức khỏe của cả số 6 và số 3, cả vấn đề sinh sản và tim mạch cũng như trầm cảm và cân nặng dễ biến động.\nNhiều ngôi sao Hollywood được hưởng lợi khi được ban cho gấp đôi năng lượng sáng tạo và cảm xúc của số 3. Meryl Streep là một trong những người hiếm hoi, có số 33/6 đúng, với ngày sinh là ngày 22 tháng 6 năm 1949 (6 + 22 + 5 = 33/6). Thượng nghị sĩ Elizabeth Warren cũng có cùng ngày sinh. Đạo diễn phim Francis Ford Coppola cũng là người có số 33/6; ông sinh ngày 7 tháng 4 năm 1939 (4 +7 + 22 = 33/6).";

const String tinh_cach_1 =
    "Năng động & hiệu quả\nCó phong cách, vui vẻ, thích kiểm soát, có khả năng thống trị, hung hăng, không nhạy cảm, đáng sợ, can đảm.";
const String tinh_cach_2 =
    "Thân thiện & khiêm tốn\nHợp tác, khiêm tốn, ngoại giao tốt, lễ độ, một người biết lắng nghe, nhút nhát, tinh tế, thường bị coi nhẹ.";
const String tinh_cach_3 =
    "Truyền cảm hứng & thu hút\nHấp dẫn, tích cực, thu hút, hướng ngoại, lạc quan, dễ nói chuyện, vui vẻ, tình cảm, dễ bị phân tán, xuề xoà.\n";
const String tinh_cach_4 =
    "Đáng tin cậy & nhất quán\nCó vẻ ngoài thực tế, đáng kính, bảo thủ, đáng tin cậy, có trách nhiệm, dè dặt, không linh hoạt, tự cao tự đại.";
const String tinh_cach_5 =
    "Nổi bật & dí dỏm\nVui vẻ, cầu tiến, lạc quan, hào hứng với mọi thứ, hấp dẫn, hướng ngoại, hào sảng, thu hút, ngoại hình trẻ trung, thiếu trách nhiệm.";
const String tinh_cach_6 =
    "Thấu hiểu & đồng cảm\nHay bảo vệ người khác, đáng tin cậy, tháo vát, thanh lịch, cầu toàn, thông cảm, có năng lực, có kỹ năng chăm sóc, trang nhã.";
const String tinh_cach_7 =
    "Nghiêm túc & bí ẩn\nCó nhận thức, quan sát tốt, thông minh, đàng hoàng, dè dặt, nội tâm, hướng nội, hay triết lý, lập dị, xa cách.";
const String tinh_cach_8 =
    "Mạnh mẽ & ấn tượng\nCó ảnh hưởng, quyền lực, tham vọng, có thẩm quyền, có đầu óc kinh doanh, có tầm nhìn xa, tự tin, tinh tế, tàn nhẫn, tham lam, tự phụ, thích kiểm soát.";
const String tinh_cach_9 =
    "Ấn tượng & cá tính\nCó năng lực, cương quyết, trung thực, ổn định, sáng tạo, thành thạo, hiệu quả, ngoại giao tốt, kiêu ngạo, đáng sợ, hay ghen tị.";
const String tinh_cach_11 =
    "Thân thiện & khiêm tốn\nHợp tác, khiêm tốn, ngoại giao tốt, lễ độ, một người biết lắng nghe, nhút nhát, tinh tế, thường bị coi nhẹ.";
const String tinh_cach_22 =
    "Đáng tin cậy & nhất quán\nCó vẻ ngoài thực tế, đáng kính, bảo thủ, đáng tin cậy, có trách nhiệm, dè dặt, không linh hoạt, tự cao tự đại.";
const String tinh_cach_33 =
    "Thấu hiểu & đồng cảm\nHay bảo vệ người khác, đáng tin cậy, tháo vát, thanh lịch, cầu toàn, thông cảm, có năng lực, có kỹ năng chăm sóc, trang nhã.";

const String van_menh_1 =
    "Con số vận mệnh 1: Người lãnh đạo và ra quyết định\nBạn thích làm theo cách riêng của mình và thường làm như vậy. Trong sự nghiệp, bạn tìm kiếm không gian phát triển để duy trì động lực, và nhiều khả năng sẽ vươn lên vị trí người chịu trách nhiệm.\nSự sáng tạo giúp bạn có kỹ năng giải quyết vấn đề nhanh chóng.\nBạn có tầm nhìn tuyệt vời và những ý tưởn sáng tạo, đồng thời xuất sắc trong việc thu hút mọi người cùng tham gia để biến ý tưởng của bạn thành hiện thực. Số 1 cũng hào hứng với các ý tưởng, thực sự hào hứng, nhưng có thể mất hứng khi đi vào chi tiết và thường phải gặp khó khăn để duy trì và kết thúc toàn bộ quá trình. Hãy nhớ đặt ra các ranh giới và đứng lên bảo vệ chính mình.\nBạn sợ thất bại. nếu không nghĩ rằng mình giỏi nhất ở lĩnh vực nào đó, bạn thậm chí sẽ không thử. Ở mặt tối tính cách, bạn có thể hách dịch, thiếu kiên nhẫn, kiêu ngạo, ích kỷ và lạm dụng sức ảnh hưởng của mình cho những mục đích xấu.\nHãy đón nhận và phát huy tài năng thiên bẩm về lãnh đạo, khả năng truyền cảm hứng, suy nghĩ độc lập và những ý tưởng độc đáo. Hãy sẵn lòng chia sẻ tính sáng tạo của bạn. Cuối cùng, Con số vận mệnh 1 đòi hỏi bạn phải tận dụng những tài năng và tạo cơ hội để hoàn thành tầm nhìn của mình.";
const String van_menh_2 =
    "Con số vận mệnh 2: Người đồng đội tốt\nCon số Vận mệnh 2 bẩm sinh là những người khéo léo, duyên dáng, giỏi chi tiết, hợp tác và kiên nhẫn. Bạn xuất sắc với tư cách là một phần của nhóm và tốt hơn trong quan hệ đối tác hơn là vị trí lãnh đạo.\nBạn có xu hướng đoán già đoán non về bản thân và thiếu tự tin vào lựa chọn của mình. Sự nhạy cảm giúp bạn làm tốt việc trong nhóm và tạo được sự cân bằng tinh tế ở nơi làm việc. Vì thích trở thành tâm điểm chú ý, bạn phải chắc chắn rằng những người khác nhau nhận ra và cảm kích những nỗ lực của bạn hay dành cho bạn sự công nhận, nêu không bạn có thể bị phớt lờ. Mọi người tin tưởng bạn và yêu mến tính cách quan tâm và hào phóng của bạn. Nếu không cảm nhận được sự tôn trọng này, bạn sẽ cảm thấy không thoải mái hoặc không làm tốt công việc.\nỞ mặt tối tính cách, bạn thường quá nhạy cảm, hay khóc, lén lút, lôi kéo và nói dối thuần thục, bộc lộ hai mặt đối lập về tính cách. Bnaj có thể trở nên đối đầu thay vì khéo léo ngoại giao.\nBạn sẽ vui vẻ nhất khi có đóng góp tích cực và năng động trong hoạt động của đội nhóm. Mang lại sự hòa hợp, cân bằng và hợp tác, khi làm việc, bạn cảm thấy thỏa mãn và vượt qua được mặt tối của mình. Cho dù đó là với gia đình, bạn bè hoặc đồng nghiệp, hãy là người hòa giải và mang lại sự ảnh hưởng hài hòa trong bất cứ tình huống nào mà bạn thấy cần thiết.";
const String van_menh_3 =
    "Con số vận mệnh 3: Nghệ sĩ và nhân vật giải trí\nCùng với sự sáng tạo quá mức, con số vận mệnh 3 có thể mắc hội chức Peter Pan và không bao giờ muốn lớn lên, bạn có một khiếu hài hước tuyệt vời và thích công việc là những trải nghiệm vui vẻ và thăng hoa. Những điều này hoàn toàn tốt, nhưng bạn cũng cần phải thực hiện trách nhiệm của mình một cách nghiêm túc. Những gì mà người khác khuyến khích là tài năng thiên bẩm của bạn có thể không phải thứ mang lại cho bạn niềm vui. Điều quan trọng là phải cố gắng giữ được sự cân bằng. Bên cạnh niềm vui, bạn cũng trải qua mọi cung bậc cảm xúc ở mức độ mãnh liệt. Cố gắng kiềm chế sự nhạy cảm của bạn và không nhìn nhận mọi thứ một cách quá cá nhân.\nNhững người khác có thể cảm thấy bạn có một cuộc sống hấp dẫn và cảm thấy ghen tị vì mọi thứ luôn suôn sẻ với bạn. Mặt khác bạn có thể cảm thấy ghen tị với bất kì ai mà bạn cho là phá huỷ tầm ảnh hưởng của bạn hoặc người có vẻ tài năng, nổi tiếng hoặc có năng khiếu hơn bạn. Hãy nhớ rằng có rất nhiều cách để thành công. \nỞ mặt tối tính cách, nhóm số 3 phải tránh quá kịch tính hoặc cảm tính, lừa dối, cố chấp và ghen tuông. Hãy tìm cách kiểm soát những cảm xúc trẻ con này và bạn sẽ trải nghiệm nhiều hơn niềm vui mà bạn đang tìm kiếm.";
const String van_menh_4 =
    "Con số vận mệnh 4: Người lập kế hoạch và nhà sản xuất \nBạn là người đáng tin cậy, có tổ chức và đúng giờ. Bạn có thể bực bội với những người không thích điều này, nhưng bạn cũng có kỹ năng để quản lý họ. Bạn có khả năng tuyệt vời trong việc giữ bình tĩnh khi đối mặt với hỗn loạn và mang lại trật tự cho mọi việc bạn làm. \nNhững thành tựu thực tế đem đến cho bạn sự hài lòng, như trả hết tiền mua xe hoặc có một ngôi nhà tươm tất. Tuy nhiên, nhu cầu kiểm soát mọi thứ là ám ảnh đối với bạn, và bạn phải học cách từ bỏ nó. \nBạn luôn là người có kế hoạch, nhưng những người khác thường không để ý đến những vất vả mà bạn đã làm. Bạn có thể chia nhiệm vụ thành từng phần nhỏ và hoàn thành từng bước, mặc dù thực tế là bạn không thích người khác can thiệp vào công việc của mình. \nỞ mặt tối tính cách, bạn có thể là một người tham công tiếc việc, cố chấp hay phản kháng và thất thường. Sự phẫn uất có thể khiến bạn trở nên tàn nhẫn. Học cách phân công công việc, trao quyền cho người khác và dành nhiều thời gian hơn để giải trí, là điều quan trọng và cần thiết đối với bạn.";
const String van_menh_5 =
    "Con số vận mệnh 5: Người tìm kiếm sự mạo hiểm\nBạn luôn có những câu chuyện để kể, những nơi để đến, những chuyến đi để thực hiện và những người để gặp. Những người khác ngưỡng mộ tinh thần mạo hiểm của bạn và muốn có cuộc sống như của bạn. Bạn phải nhớ đừng đưa mọi thứ đi quá xa và cuộc sống vẫn thú vị mà không bị hủy hoại.\nĐể đạt được sự thỏa mãn trong sự nghiệp cụa mình, bạn sẽ cần rất nhiều thứ, vì vậy cuộc sống văn phòng có thể không phù hợp với bạn. Tính cách lôi cuốn và năng khiếu thu hút sự chú ý của bạn phù hợp với công việc bán hàng, tiếp thị hoặc quảng cáo.\nBạn có thể bị cuốn vào những bộ phim truyền hình hoặc những câu chuyện phiếm, đôi khi tự tạo nên một kịch bản để giải trí, Vì dễ trở nên buồn chán, bạn có thể thấy xung quanh mình là những người luôn rơi vào khủng hoảng. Để tránh tình trạng này làm tiêu hao năng lượng tuyệt vời của bạn, hãy cố gắng tìm hiểu sâu hơn về bản thân và người khác.\nỞ mặt tối tính cách, bạn có thể bốc đồng, bồn chồn, thẳng thắn, thô lỗ và thậm chí là thô tục. Điều khiến bạn sụp đổ có thể là những lựa chọn điên rồ bạn đưa ra mà không suy  nghĩ đến hậu quả. Bạn cũng cần cẩn trọng với xu hướng tự hủy hoại bản thân.";
const String van_menh_6 =
    "Con số vận mệnh 6: Người theo chủ nghĩa hoàn hảo\nMột trong những phẩm chất tốt nhất của bạn là lòng trung thành mặc dù, đáng buồn thay, nó hiếm khi được đáp lại. Con người bạn có thể đã được định hình bởi trách nghiệm gia đình từ khi còn nhỏ. Có một ngôi nhà hạnh phúc và ổn định là điều quan trọng đối với bạn, và bạn cũng xuất sắc trong các lĩnh vực liên quan đến gia dình. Bạn là một bậc cha mẹ tuyệt vời và nếu không có con, bạn sẽ dành nhiều công sức cho việc chăm sóc động vật.\nBạn là người có óc xét đoán, chín chắn và đáng tin cậy. Trách nhiệm nuôi dưỡng tâm hồn bạn. Bạn có khả năng đánh giá tốt về tính cách và đưa ra những lời khuyên tuyệt vời, đóng vai trò cố vấn cho bạn bè (và có thể cả về chuyên môn). Bạn muốn làm đẹp môi  trường xung quanh mình, những thứ xinh đẹp mang lại cho bạn niềm vui và sự thoải mái.\nMặt tối tính cách của bạn là sự tự mãn, mỉa mai và tự phụ, suy nghĩ cho rằng không ai có thể làm tốt công việc bằng bạn. Những người khác có thể nhầm lẫn các tiêu chuẩn cao mà bạn đặt ra cho  bản thân thành ham muốn cạnh tranh hoặc trịch thượng. Bạn có xu hướng can thiệp, lo lắng và luôn tìm kiếm sự công nhận. Đừng quá chú tâm vào suy nghĩ hoặc vấn đề của người khác";
const String van_menh_7 =
    "Con số vận mệnh 7: Người có trực giác thông minh \nBạn toả ra phẩm chất của sự trầm lặng. Bạn suy nghĩ sâu sắc về mọi thứ và sự mơ mộng có thể khiến bạn trở thành thiên tải triết học hoặc công nghệ. Bạn đĩnh đạc, dè dặt, tinh ý, tinh tế và duy tâm. Bạn có thể ở một mình và không cô đơn, dù đây là điều khó khăn với nhiều con số vận mệnh khác.\nTrực giác của bạn mạnh đến mức bạn có thể nhìn thấy suy nghĩ của người khác. Những giấc mơ của bạn có khả năng tiên tri. Bạn có trí nhớ tuyệt vời và quan tâm đến lịch sử, các bộ sưu tập và quá khứ. Bạn xuất sắc trong một lĩnh vực cụ thể và có thể trở thành chuyên gia thực sự. \nNhóm này thường cảm thấy rằng trong quá trình trưởng thành của mình dường như có những bí mật từ cha mẹ. Ngay cả khi điều này là để bảo vệ bạn, cảm giác đó vẫn hình thành và nuôi dưỡng một sự nghi ngờ thực sự trong bạn. Bạn là người giữ bí mật và có xu hướng hơi cô độc. Bạn làm việc chăm chỉ, đôi khi trong nhiều năm, hướng tới mục tiêu trong cuộc sống và công việc của bạn. \nMặt tối tính cách của bạn là sự nghi ngờ, không trung thực, hoang tưởng, lén lút và ghen tị. Bạn có cảm giác tâm linh mạnh mẽ, hay có niềm tin mạnh mẽ vào bất cứ điều gì mà cá nhân bạn thấy có điểm tương đồng, tin rằng điều đó sẽ tạo nền tảng, sự cân bằng và giúp bạn phát huy hết khả năng của mình. Bạn là ngừoi rất khoa học hoặc rất duy tâm, tuy nhiêm có một số người có thể tạo ra sự cân bằng giữa hai điều này. Hãy vun đắp, nuôi dưỡng ít nhất là một vài mối quan hệ thân thiết. Điều quan trọng là phải chia sẻ trí tuệ và kiến thức rộng lớn của bạn với thế giới.";
const String van_menh_8 =
    "Con số vận mệnh 8: Người điều hành \nBạn sinh ra để thành công và dồi dào về tài chính. Bạn đã sớm học về quyền lực và địa vị và cần trở thành một người có chức quyền trong sự nghiệp mình đã chọn để cảm thấy thoả mãn. May mắn thay, bạn là một nhà lãnh đạo và người có khả năng ảnh hưởng bẩm sinh. \nBạn yêu thích thành tích nhưng hãy cẩn trọng, bạn có thể không bao giờ cảm thấy hài lòng, luôn muốn làm nhiều hơn, nhiều hơn nữa để có nhiều và nhiều hơn nữa. Bạn có xu hướng coi trọng vật chất, nhưng lòng tốt và sự hào phòng mới là di sản đáng quý hơn.\nThất bại là điều huỷ diệt với bạn, nhưng không cố gắng còn tồi tệ hơn, vì vậy bạn phải dám đối mặt với nỗi sợ hãi của mình. Theo thời gian, bạn sẽ nhận ra mọi người đánh giá, phản hồi về con người của bạn chứ không phải những gì bạn làm hay những gì bạn có.\nMặt tối tính cách của bạn là thiếu sự kiên nhẫn, không khoan dung, tàn nhẫn và đôi khi là bạo lực. Bạn có thể lạm dụng chất kích thích và gặp các vấn đề về tài chính, Bạn phải luôn tìm kiếm sự cân bằng. Những mong muốn, khao khát của bạn sẽ được lấp đầy khi bạn mang nền tảng tâm linh và thế giới vật chất của mình.";
const String van_menh_9 =
    "Con số Vận mệnh 9: Người có tấm lòng nhân đạo\nBạn có thể thu phục hầu hết mọi người bằng khiếu hài hước, tính cách hướng ngoại và sự quyến rũ của mình. Bạn là người có tầm nhìn xa và có thể truyền cảm hứng cho những người khác tham gia vào một phong trào giúp thế giới trở nên tốt đẹp hơn. Bạn có thể lí tưởng hóa mọi thứ và thậm chí ngây thơ về động cơ của người khác. Bạn là người dễ gây ấn tượng và dễ hình thành thói quen, có thể bao gồm lạm dụng chất kích thích.\nBạn là người kiên nhẫn, nhân ái và lãng mạn. Bạn muốn được thế giới công nhận và bí mật tìm kiếm sự nổi tiếng. Chia sẻ tài năng của mình, giúp đỡ nhân loại, dạy dỗ, tư vấn và chữa lành cho mọi người là những điều nuôi dưỡng tâm hồn bạn. Trong khi theo đuổi mong muốn giải cứu thế giới, hãy đảm bảo bạn không bỏ bê những người thân thiết của mình.\nMặt tối tính cách của bạn có thể là tính chiếm hữu, ủ rũ, nhút nhát, ngây thơ và dễ bồn chồn. Là người nghiện mua sắm, bạn rất dễ phung phí tiền bạc.";
const String van_menh_11 =
    "Con số Vận mệnh Vua 11: Người có trực giác nhạy bén\nSố này mang thông điệp mạnh mẽ. Là người cực kỳ nhạy cảm, có trực giác và khả năng nhận biết nhạy bén, bạn toát ra vẻ mạnh mẽ, tinh tế và thanh lịch. Bạn sẽ trải nghiệm sự hướng dẫn mang tính tâm linh, và khả năng lãnh đạo bẩm sinh giúp bạn dễ dàng thu hút đồng đội hoặc danh tiếng.\nBạn đưa ra quyết định bằng sự kết hợp khó nắm bắt giữa logic, trực giác và cảm xúc. Bạn nhận thức rõ sự khác biệt của bản thân và theo thời gian, bạn sẽ nắm bắt trọn vẹn những món quà đặc biệt của mình để đánh thức và soi sáng cho những người khác.\nỞ mặt tối tính cách, bạn có thể bị thao túng và sử dụng quyền lực của mình cho những nỗ lực đáng nghi ngờ về mặt đạo đức. Bạn có thể gặp khó khăn khi phân tách giữa tưởng tượng và thực tế. Bạn thường cảm thấy không ai có thể đáp ứng được kỳ vọng của bạn.";
const String van_menh_22 =
    "Con số vận mệnh vua 22: Kiến trúc sư tài ba \nBạn có khả năng nhận thức được bức tranh toàn cảnh từ khi còn nhỏ và luôn ước mơ lớn lao. Bạn có nhiều khả năng thành công nhất trong tất cả các con số vận mệnh và mong muốn để lại dấu ấn thực sự trên thế giới. Bạn có thể khai thác những khả năng đặc biệt của mình khi trưởng thành, khi bạn thực sự bắt đầu hiểu được khả năng mình được ban cho. Bạn sẽ đạt được những điều lớn lao. \nỞ mặt tối của tính cách, bạn có thể là người ranh mãnh và thâm hiểm trong kinh doanh, phá hoại thậm chí là xấu xa. Bạn phải luôn sử dụng quyền hạn của mình cho mục đích tốt.";
const String van_menh_33 =
    "Con số vận mệnh vua 33: Nhân vật có tầm ảnh hưởng\nĐể là người có con số vận mệnh 33/6 thực sự, bạn phải có con số linh hồn là 11 hoặc 22 hoặc con số tính cách là 11 hoặc 22.\nCon số vận mệnh 33 mang một sứ mệnh to lớn cần phải hoàn thành, nhưng bạn là người có trách nhiệm, vì vậy bạn sẵn sàng chấp nhận thử thách. Bạn có khả năng sáng tạo vượt trội, khả năng giao tiếp, sự chân thành và lòng trắc ẩn. Phục vụ người khác sẽ tiết lộ khả năng thiên bẩm của bạn. Là người tốt bụng và khiêm tốn, bạn cho đi mà không mong nhận lại. Bạn là người có tầm nhìn xa, tràn đầy niềm vui và lòng trắc ẩn, và bạn dễ dàng có được những mối quan hệ chân thành.\nBạn là một nhân vật có tầm ảnh hưởng. Số phận của bạn là trở thành một tấm gương về sức mạnh thực sự của tình yêu và lòng trắc ẩn đối với thế giới. Bạn là một người trợ giúp và một người chữa lành.\nMặt tối tính cách của số 33 là tinh thần 'tử vì đạo', và bạn có thể hay phàn nàn. Bạn thường gánh chịu nỗi đau hoặc vết sẹo của người khác. Bạn sẽ tìm được phần thưởng tuyệt vời cho mình khi sử dụng khả năng chữa lành, an ủi thiên bẩn để mọi người giúp đỡ người khác và cung cấp công cụ để mọi người tự giúp mình";

const String linh_hon_1 =
    "Con số Linh hồn 1:Người thu hút người khác\nVới phong cách và hình ảnh độc đáo, nhóm người có số này sẽ là người dẫn đầu trong các mối quan hệ. Bạn có xu hướng xây dựng những bức tường bảo vệ và có thể có tâm lý “Tôi sẽ làm tổn thương bạn trước khi bạn có thể làm tổn thương tôi”. Trong sâu thẳm, bạn là một người lãng mạn trong vô vọng.\nSự quyến rũ của bạn sẽ đưa bạn đi xa, nhưng bạn mong đợi sẽ tìm thấy điểm tương đồng ở người bạn đời của mình và muốn người khác cũng thông minh và độc lập như bạn. Bạn truyền cảm hứng cho sự đổi mới và không bị thu hút tham gia vào những điều thông thường.";
const String linh_hon_2 =
    "Con số Linh hồn 2: Người tận tâm, nhiệt tình\nCảm thấy tốt hơn khi ở cùng người khác thay vì một mình, những người có con số Linh hồn 2 sẽ không độc thân quá lâu. Họ cam kết và mong đợi điều tương tự từ đối phương, đối tượng kết hôn của mình.\nHọ có thể làm bất cứ điều gì cần thiết để giữ hòa khí. Họ là người khéo léo và tốt bụng, có thể nhìn thấy cả hai mặt của tình huống và thích là người hỗ trợ trong mối quan hệ hơn là người dẫn dắt.\nVì cực kì nhạy cảm nên những lời chỉ trích có thể gây tổn hại sâu sắc đối với họ. Họ cũng là người tận tâm, cống hiến và điều quan trọng nhất là họ cảm thấy được trân trọng.";
const String linh_hon_3 =
    "Con số Linh hồn 3: Người có sức quyến rũ\nMê hoặc và quyến rũ, Con số Linh hồn 3 khiến người khác cảm thấy bật cười và cảm thấy họ thật đặc biệt với tính cách nổi bật của họ. Bạn có xu hướng chạy theo những cuộc vui và đấu tranh với tâm lý “cỏ bên đồi kia luôn xanh hơn” , điều này có thể khiến bạn trở nên thiếu độ tin cậy trong các mối quan hệ.\nBạn có thể che giấu cảm xúc thật của mình bằng sự hài hước và nói liên tục . Nếu bạn không vui, người khác sẽ nhận ra qua lời nói của bạn, điều này có thể giống như những nhát dao, được sử dụng với mục đích gây tổn thương.\nBài học của bạn là luôn cho người khác sự công nhận mà họ xứng đáng được nhận, không coi mọi thứ là điều hiển nhiên và mọi người sẽ mãi luôn bên bạn.";
const String linh_hon_4 =
    "Con số Linh hồn 4: Người bộc trực\nCon số Linh hồn 4 là những người có thể tỏ ra lạnh lùng hoặc xa cách . Cảm xúc dễ biến động và số 4 thích kiểm soát chúng cùng với mọi thứ khác. Họ luôn tiếp cận mọi thứ thực tế, kể cả tình yêu, và có vẻ là người không lãng mạn cho lắm.\nHọ có thể tạo ra sự lãng mạn, nhưng cử chỉ hoặc bữa tối lãng mạn đó sẽ được lên kế hoạch và thực hiện một cách hoàn hảo. Họ thích cho và nhận những món quà thiết thực hơn là những món quà phù phiếm.\nPhẩm chất tốt nhất của họ là bạn đáng tin cậy và sẽ xây dựng một cuộc sống có trật tự, hỗ trợ mạnh mẽ cho bạn đời của mình. Họ tìm kiếm một tình yêu ổn định với người mà họ tin tưởng để giúp họ xây dựng ước mơ của mình.";
const String linh_hon_5 =
    "Con số Linh hồn 5: người có tâm hồn tự do\nTự do là yếu tố cần thiết cho hạnh phúc của Con số Linh hồn 5. Với niềm đam mê sâu sắc đối với sự thay đổi, du lịch và phiêu lưu, bạn tìm kiếm cảm giác không bị gò bó, giới hạn trong các mối quan hệ. Nhóm này khó giữ lời hứa và cũng không tuân thủ tốt các yêu cầu, mệnh lệnh.\nSố 5 thường bị chi phối bởi các giác quan nên quan hệ tình dục là điều đặc biệt quan trọng đối với nhóm này. Bạn luôn muốn sự đa dạng, và điều đó mở rộng đến cả phòng ngủ. Những thú vui xúc cảm mang cho bạn niềm hạnh phúc nhưng cũng có thể dẫn đến sự vô độ và lạm dụng.\nCon số Linh hồn 5 thường có xu hướng kết hôn muộn hơn. Họ chống lại những ràng buộc tình cảm và những cam kết lâu dài.";
const String linh_hon_6 =
    "Con số linh hồn 6: Người yêu thương\nMong muốn lớn nhất của những con người có Con số Linh hồn 6 là yêu và được yêu. Đa cảm, kiên nhẫn, từ bi và thấu hiểu, bạn là người bạn đời tuyệt vời và khiến tình yêu trở nên không quá phức tạp.\nSố 6 có xu hướng lý tưởng hóa tình yêu, tạo ra hình ảnh về một cuộc sống tươi đẹp và hoàn hảo, sau đó phấn đấu vì nó. Bạn mong đợi sự cam kết trong các mối quan hệ. Số 6 cần cảm thấy được phụ thuộc, thích lắng nghe và đưa ra lời khuyên, hỗ trợ.\nVới tình yêu sâu sắc dành cho tổ ấm của mình, số 6 thường chọn có con, dĩ nhiên không phải lúc nào cũng có thể như vậy.";
const String linh_hon_7 =
    "Con số linh hồn 7:Người bí ẩn\nSự thông minh là điểm quyến rũ và nét tinh tế của bạn. Bạn tạo cho người khác ấn tượng rằng bạn thichs giữ mọi thứ riêng tư. Con số linh hồn này có thể chọn một cuộc sống cô độc, quan tâm đén việc của bản thân hơn là của người khác. Nếu bạn yêu đương hay kết hôn, đó sẽ là khi bạn đã trưởng thành và đó phải là một mối quan hệ rất riêng tư và an toàn. Bạn cảm thấy việc trở thành nhà sư hoặc thầy là một ý tưởng hấp dẫn.\nBạn thích nói về sự thật sự hơn là cảm giác và cảm xúc không thể đoán trước. Cách tiếp cận khách quan của bạn đối với mối quan hệ lãng mạn có thể gây ra sự ngờ vực, vì người kia có thể cảm thấy bạn đang từ chối họ.Trở nên dễ bị tổn thương về mặt cảm xúc và tạo dựng những kết nối sâu sắc là điều nằm ngoài vùng an toàn của bạn nhưng cần thiết cho một cuộc sống viên mãn";
const String linh_hon_8 =
    "Con số linh hồn 8: Người phấn đấu\nSố 8 thích học từ khó khăn và các vấn đề của trái tim cũng không ngoại lệ. Bạn có thể thấy mình đang ở trong những mối quan hệ với cùng một kiểu người nhiều lần. Điều này có thể gây kiệt quệ về mặt cảm xúc và tài chính. Hãy cố tìm ra hình mẫu lãng mạn của bạn và chấm dứt vòng theo đuổi luẩn quẩn.\nSố 8 được hưởng tiện nghi, vật chất và giàu sang. Điều quan trọng đối với bạn là người khác cảm nhận bạn là người thành công. Bạn có ước mơ lớn và không ngại vất vả. Bạn cần được thử thách (và phần thưởng cho việc vượt qua thử thách), ngay cả trong các mối quan hệ, nếu không bạn sẽ rơi vào trạng thái rung động thấp, trở nên tàn bạo, độc ác, chán nản và thất vọng. Người bạn đời lý tưởng của bạn phải hấp dẫn, có năng lực và được định hướng như bạn.\nCho dù có chủ ý hay không, số này có xu hướng kết hôn hoặc kết đôi với người có nguồn lực có thể hỗ trợ tầm nhìn và nhu cầu thành công về mặt vật chất của bạn.\nHãy nhớ rằng không có chỗ cho đạo đức giả trong tình yêu, hãy đối xử với đối phương của bạn như cách bạn muốn được đối xử.";
const String linh_hon_9 =
    "Con số linh hồn 9: Người có lòng bác ái\nCon số Linh hồn 9 là những người có mong muốn tình yêu phổ quát và thực sự quan tâm đến hạnh phúc của nhân loại. Là những linh hồn già dặn, số 9 khôn ngoan, và có tài năng trực giác đặc biệt\nHọ là những người chu đáo và luôn đoán trước được nhu cầu cả người bạn đời, đối xử với họ như là vua hoặc hoàng hậu. Trong mối quan hệ với số 9, bạn thường sẽ nhận thấy sự chênh lệch tuổi tác đáng kể\nSố 9 thầm mơ ước có ảnh hưởng lớn đến thế giới và thậm chí có thể trờ nên nổi tiếng, mặc dù bạn sở hữu vẻ đẹp của sự khiêm tốn. Vì hiểu biết và rộng lượng nên bạn thường bị giằng xé giữa nhu cầu của bản thân và nhu cầu của người khác.\nSống cảm xúc và nhạy cảm, bạn cũng có thể hay chỉ trích và thất thường. Bạn sẽ thất vọng khi mọi người không thể đáp ứng kỳ vọng cao của bạn hoặc không thể tự giúp đỡ chính mình khi có cơ hội";
const String linh_hon_11 =
    "Con số Linh hồn 11: Người tận tâm, nhiệt tình\nCảm thấy tốt hơn khi ở cùng người khác thay vì một mình, những người có con số Linh hồn 2 sẽ không độc thân quá lâu. Họ cam kết và mong đợi điều tương tự từ đối phương, đối tượng kết hôn của mình.\nHọ có thể làm bất cứ điều gì cần thiết để giữ hòa khí. Họ là người khéo léo và tốt bụng, có thể nhìn thấy cả hai mặt của tình huống và thích là người hỗ trợ trong mối quan hệ hơn là người dẫn dắt.\nVì cực kì nhạy cảm nên những lời chỉ trích có thể gây tổn hại sâu sắc đối với họ. Họ cũng là người tận tâm, cống hiến và điều quan trọng nhất là họ cảm thấy được trân trọng.\nVới Con số Linh hồn 11/2 cảm xúc có thể dao động mãnh liệt. Năng lượng gấp đôi số 1 có thể dẫn đến sự ích kỷ. Đảm bảo rằng bạn đang sử dụng khả năng thuyết phục của mình vì một mục đích xứng đáng, không phải vì sự thao túng và lợi ích các nhân.\nBạn mang lại chất lượng tinh thần sâu sắc cho bất kì mối quan hệ nào.";
const String linh_hon_22 =
    "Con số Linh hồn 22: Người bộc trực\nCon số Linh hồn 4 là những người có thể tỏ ra lạnh lùng hoặc xa cách . Cảm xúc dễ biến động và số 4 thích kiểm soát chúng cùng với mọi thứ khác. Họ luôn tiếp cận mọi thứ thực tế, kể cả tình yêu, và có vẻ là người không lãng mạn cho lắm.\nHọ có thể tạo ra sự lãng mạn, nhưng cử chỉ hoặc bữa tối lãng mạn đó sẽ được lên kế hoạch và thực hiện một cách hoàn hảo. Họ thích cho và nhận những món quà thiết thực hơn là những món quà phù phiếm.\nPhẩm chất tốt nhất của họ là bạn đáng tin cậy và sẽ xây dựng một cuộc sống có trật tự, hỗ trợ mạnh mẽ cho bạn đời của mình. Họ tìm kiếm một tình yêu ổn định với người mà họ tin tưởng để giúp họ xây dựng ước mơ của mình.\nLà người có Con số Linh hồn 22/4 , họ mong muốn để lại một di sản cho thế hệ sau. Để hoàn thành sứ mệnh này, họ phải cam kết hết mình với nó .";
const String linh_hon_33 =
    "Con số linh hồn 33: Người yêu thương\nMong muốn lớn nhất của những con người có Con số Linh hồn 6 là yêu và được yêu. Đa cảm, kiên nhẫn, từ bi và thấu hiểu, bạn là người bạn đời tuyệt vời và khiến tình yêu trở nên không quá phức tạp.\nsố 6 có xu hướng lý tưởng hóa tình yêu, tạo ra hình ảnh về một cuộc sống tươi đẹp và hoàn hảo, sau đó phấn đấu vì nó. Bạn mong đợi sự cam kết trong các mối quan hệ. Số 6 cần cảm thấy được phụ thuộc, thích lắng nghe và đưa ra lời khuyên, hỗ trợ.\nVới tình yêu sâu sắc dành cho tổ ấm của mình, số 6 thường chọn có con, dĩ nhiên không phải lúc nào cũng có thể như vậy.\nNgười có Con số Linh hồn 33/6 muốn dấy lên sự rung động tình yêu của thế giới. Bạn là người giàu cảm xúc và muốn mang lại sự hiểu biết cho thế giới thông qua tình yêu.";

const String ngay_sinh_1 =
    "Con số ngày sinh 1\nBạn là người độc lập, thích cạnh tranh và là một nhà lãnh đạo bẩm sinh. \nBạn là người sáng tạo với rất nhiều ý tưởng độc đáo và bạn thích nổi bật. \nBạn chủ động và có thể khuấy động, tạo cảm hứng cho mọi người. \nBạn cũng có thể cứng đầu, ích kỷ và thất thường. \nBài học tuyệt vời của bạn là học về ranh giới, chia sẻ và làm việc theo nhóm";
const String ngay_sinh_2 =
    "Con số ngày sinh 2\nTốt bụng, kiên nhẫn, nhạy cảm và trực giác nhạy bén, bạn làm việc theo cặp tốt hơn là một mình. \nBạn là một đồng đội hòa đồng, chu đáo và luôn hỗ trợ người khác. \nBạn không khao khát ánh đèn sân khấu. \nBài học cho bạn là học cách đứng lên vì chính mình";
const String ngay_sinh_3 =
    "Con số ngày sinh 3\nBạn là người thân thiện và tràn đầy năng lượng, và khả năng sáng tạo của bạn không có giới hạn. Bạn là người rất thân thiện, hòa đồng, vui vẻ và là người thích cuộc sống của những bữa tiệc. Bài học của bạn là học cách quản lý cảm xúc và ngừng tìm kiếm sự thỏa mãn tức thì.";
const String ngay_sinh_4 =
    "Con số ngày sinh 4\nBạn thực tế, đáng tin cậy, chăm chỉ, trung thực và công bằng. Bạn là người có tổ chức và hành động nhanh chóng. Bạn thích lập kế hoạch và luôn muốn biết những gì sẽ xảy ra . bài học của bạn là học cách giải phóng quyền kiểm soát. Nợ Nghiệp 13/4 sẽ khuyến khích bạn đấu tranh với sự trì hoãn.";
const String ngay_sinh_5 =
    "Con số ngày sinh 5\nBạn thôi thúc bởi lời kêu gọi cảm giác phiêu lưu và sự buồn chán là \"gót chân Achilles\" của bạn. Cuộc sống phải luôn thú vị hoặc bạn sẽ thoát ra và bước tiếp. Bạn là người tháo vát, dám chấp nhận sự thay đổi, cà đôi khi bốc đồng. Bài học của bạn là học cách chịu trách nhiệm. Nợ nghiệp 14/5 đưa bạn vào cuộc chiến để đánh bại sự nghiệp ngập và vô độ.";
const String ngay_sinh_6 =
    "Con số ngày sinh 6\nBạn có trách nhiệm và hướng về gia đình. Bạn cũng yêu động vật. Trung thành, cầu toàn và chu đáo đều là một phần bản chất của bạn(mặc dù bạn có xu hướng can thiệp vào những công việc không phải của mình). Bạn sẽ học được cách vượt qua sự phản bội và chỉ quan tâm đến việc của bản thân mình.";
const String ngay_sinh_7 =
    "Con số ngày sinh 7\nBạn tập trung quá nhiều vào phân tích mọi thứ, cố gắng tìm ra ý nghĩa sâu sắc trong tất cả những gì bạn làm. Bạn thích đọc và ham mê học hỏi. Bạn luôn đặt ra các giả thuyết. Bạn vừa tò mò vừa đòi hỏi sự riêng tư. Bài học của bạn là học cách làm việc với người khác một cách vị tha. Nợ Nghiệp 16/7 sẽ có nhiều bài học dạy bạn khi bạn sống thả lỏng hơn.";
const String ngay_sinh_8 =
    "Con số ngày sinh 8\nThành công là điều quan trọng và có thể đạt được với bạn. Bạn thích xe đẹp, đồ hiệu và bất cứ thứ gì có tên tuổi, Bài học của bạn là tìm sự cân bằng giữa tinh thần và vật chất, đồng thời học tính kiên nhẫn và lòng trung thành. Không phải lúc nào bạn cũng phải trả qua khó khăn để học hỏi.";
const String ngay_sinh_9 =
    "Con số ngày sinh 9\nBạn hào phóng, sáng tạo, nhạy cảm, khoan dung, cởi mở và có cách tiếp cận độc đáo để giải quyết vấn đề. Bạn là người có tấm lòng nhân ái với mong muốn làm cho thế giới trở nên tốt đẹp hơn. Hãy cẩn thận với việc tỏ ra biết tất cả hoặc ra vẻ trịch thượng. Bài học cho bạn là học cách tha thứ và buông bỏ.";
const String ngay_sinh_11 =
    "Con số Vua 11 (Ngày sinh của bạn là ngày 11 hoặc 29)\nBạn sở hữu nhiều tài năng thiên bẩm. Bạn tốt bụng, và là người biết điều tiết bầu không khí chung. Bạn có khả năng phát hiện xu hướng và vượt qua ranh giới. Bạn cũng có thể bị lôi kéo và trở nên cực đoan. Bài học cho bạn là học tính quyết đoán và không từ bỏ ước mơ của mình";
const String ngay_sinh_22 =
    "Con số Vua 22 (Ngày sinh của bạn là ngày 22)\nBạn là một nhà xây dựng thành thạo. Nhiều công trình hoành tráng lần đầu tiên được hoàn thành bởi những người có Con số Ngày sinh này! Bạn có thể là người trẻ nhất hoặc người đầu tiên đạt được một cột mốc quan trọng. bạn suy nghĩ hướng ngoại và có tầm nhìn thực sự. Bạn là người mạnh mẽ và luôn tiềm ẩn nguy cơ lạm dụng sức mạnh này. Bài học của bạn liên quan đến cái tôi.";

const String ngay_ca_nhan_1 =
    "Đây là ngày của những ý tưởng tuyệt vời, là ngày để bắt đầu một điều gì đó. Tập trung vào bản thân, nhưng đừng ích kỷ hay bướng bỉnh. Đã đến lúc phải dứt khoát, tham vọng và tự tin hành động.";
const String ngay_ca_nhan_2 =
    "Hãy kiên nhẫn và tập trung vào chi tiết. Làm việc dựa trên các mối quan hệ và hợp tác. Đây là một ngày nhẹ nhàng. Bạn sẽ cảm thấy nhạy cảm và có thể có những giấc mơ sống động.";
const String ngay_ca_nhan_3 =
    "Hãy sáng tạo, dành thời gian cho bạn bè và giao tiếp. Chấp nhận bất kỳ lời mời nào bạn nhận được. Thực hành lòng biết ơn. Tránh hành vi đặc quyền. Đây là một ngày may mắn!";
const String ngay_ca_nhan_4 =
    "Học cách có tổ chức, quy củ. Chú trọng đến sức khỏe. Tránh sự cứng nhắc, kín kẽ hoặc kiểm soát. Đừng trì hoãn. Tập trung vào chi tiết để tiến gần hơn đến mục tiêu của bạn. Làm theo các quy tắc nếu không bạn sẽ phải đối mặt với hậu quả.";
const String ngay_ca_nhan_5 =
    "Hãy thay đổi, mở rộng và thúc đẩy các mối quan hệ. Tránh hành xử quá bốc đồng. Tập trung năng lượng. Sẵn sàng đón nhận sự thay đổi; ngày của bạn có thể không diễn ra như kế hoạch.";
const String ngay_ca_nhan_6 =
    "Quan tâm đến gia đình, vật nuôi và ngôi nhà của bạn. Trang trí và làm đẹp xung quanh. Hãy lưu tâm đến ý kiến mạnh mẽ của riêng bạn. Tập trung vào các vấn đề trong nhà và trao đi năng lượng, chăm sóc, nuôi dưỡng của mình. Gặp bác sĩ trị liệu, làm tóc, học thêm điều gì đó mới.";
const String ngay_ca_nhan_7 =
    "Đây là thời gian cho sự yên tĩnh. Nghỉ ngơi và nhìn nhận lại mọi thứ. Suy ngẫm. Dành thời gian ở ngoài trời, gần với thiên nhiên hoặc đọc sách. Bạn có thể cảm thấy muốn ở một mình. Hãy ưu tiên chăm sóc bản thân trong ngày này.";
const String ngay_ca_nhan_8 =
    "Quản lý tiền của bạn, yêu cầu tăng lương, thu nợ, thanh toán hóa đơn, trả phí. Hãy cẩn thận để không lặp lại bài học hoặc sai lầm. Chú tâm đến công việc để tiến bộ và thành công. Không có bài học Nghiệp trong ngày này. Bạn có thể gặp vấn đề với chính quyền.";
const String ngay_ca_nhan_9 =
    "Kết thúc mọi thứ. Hãy giải phóng và bao dung. Thực hiện những việc làm tử tế ngẫu nhiên. Cho đi một thứ gì đó. Hoàn thiện các dự án và hoàn tất các chi tiết dang dở.";

const String thang_ca_nhan_1 =
    "Hãy bắt đầu! Bắt đầu một cái gì đó mới và liên kết với năng lượng ở chu kỳ Trăng non";
const String thang_ca_nhan_2 =
    "Trọng tâm của tháng này sẽ là các mối quan hệ. Hãy hợp tác và kiên nhẫn";
const String thang_ca_nhan_3 =
    "Tháng này sẽ xảy ra một sự kiện quan trọng với bạn. Hãy thoải mái giao lưu, vui chơi và tìm cách giải tỏa thật sáng tạo. Cảm xúc của bạn sẽ tăng cao.";
const String thang_ca_nhan_4 =
    "Đừng trì hoãn! Hãy quan tâm đến chi tiết và bất kỳ điều gì bạn chưa hoàn thiện. Luôn quan tâm đến sức khỏe của bạn ";
const String thang_ca_nhan_5 =
    "Tránh buôn chuyện hay hóng hớt chuyện phiếm. Đón nhận và nắm bắt sự thay đổi. Bạn có thể vụng về và dễ gặp tai nạn trong tháng này.";
const String thang_ca_nhan_6 =
    "Làm đẹp môi trường xung quanh bạn. Tập trung vào gia đình và vật nuôi.";
const String thang_ca_nhan_7 =
    "Trở thành chuyên gia ở một lĩnh vực nào đó. Dành thời gian để tra cứu và học hỏi. Chăm sóc  bản thân là điều quan trọng lúc này. Bạn có thể cảm thấy tách biệt và ẩn dật.";
const String thang_ca_nhan_8 =
    "Tháng này mang đến vòng xoay tiền bạc: Có thể là một khoản tiền thưởng hoặc các khoản tiền bất ngờ đến với bạn. Hãy coi chừng, nó sẽ nhanh chóng rời đi do phát sinh những chi phí không lường trước được.";
const String thang_ca_nhan_9 =
    "Tha thứ, loại bỏ mọi thứ, cho đi thời gian và tiền bạc của bạn và thực hiện những việc làm tử tế bất kỳ. Đón nhận phần thưởng của bạn! Liên kết với năng lượng ở chu kỳ Trăng tròn để giải phóng và nhường chỗ cho những may mắn mới sẽ đến trong chu kì 9 tháng tiếp theo.";

const String nam_ca_nhan_1 =
    "Năm Cá nhân 1 : Năm khởi đầu\nĐây là lúc để tiến về phía trước! Đó là một sự thay đổi đáng hoan nghênh sau Năm 9 của bạn khi bạn đang dần buông bỏ và nhường chỗ cho những khởi đầu mới. \nVới hiệu ứng hào quang, bạn vẫn sẽ cảm thấy có một vài thứ rơi rớt mà bạn đã bỏ qua để “tiễn biệt” năm cũ. Bạn có thể cảm thấy Năm 1 là một khởi đầu chậm chập. Nhưng đây chính là thời điểm hoàn hảo để bạn đặt ra dự định, gieo hạt phát triển ý tưởng và bắt đầu hành động để biến chúng thành hiện thực. Những gì xảy ra bây giờ sẽ ảnh hưởng trực tiếp đến phần thưởng hoặc thành quả của bạn trong chín năm tới.\nBạn có thêm sự tự tin mới. Bạn có động lực và thực sự có thể làm cho mọi thứ xảy ra. Năm này sẽ là năm của chuyển động, tiến bộ và sẽ trôi qua nhanh chóng. Bạn có thể thấy mình quyết liệt, tích cực hơn hiện tại. Hãy nhớ giữ mối quan hệ tốt với những người khác, đừng cứng đầu và hãy chủ động yêu cầu giúp đỡ khi cần.";
const String nam_ca_nhan_2 =
    "Năm Cá nhân 2: Năm của các mối quan hệ và sự nhẫn nại \nNăm này là thời gian để nuôi dưỡng những hạt giống bạn đã gieo vào Năm 1. Thời gian của Paran bạn sẽ được sử dụng vào sử dụng tốt để chăm sóc những ý moo tưởng lớn mà bạn đã đề ra vào năm trước.\nBạn sẽ có những kết nối mạnh mẽ và gặp gỡ những người có thể giúp bạn đạt được mục tiêu và ước mơ của mình. Đây là thời điểm tuyệt vời cho những mối quan hệ lãng mạn và xây dựng gia đình.\nNăm này diễn biến chậm hơn một chút so với năm trước, và sự kiên nhẫn và khả năng thỏa hiệp của bạn sẽ được thử thách. Bạn cũng sẽ trải qua những việc liên quan đến sự nhạy cảm.";
const String nam_ca_nhan_3 =
    "Năm Cá nhân 3 : Năm của các sự kiện xã hội & cảm xúc\nNăm Cá nhân 3 của bạn sẽ là một năm của các hoạt động và sự kiện xã hội, và bạn có thể thấy mình nổi tiếng hơn bình thường. Đây là năm của những kết nối tuyệt vời : Hãy sẵn sàng đón nhận những lời mời. Vũ trụ muốn tạo một số kết nối cho bạn trong năm nay! Hãy để chúng xảy ra. Chấp nhận mọi lời mời bạn nhận được và gặp gỡ nhiều người nhất có thể. \nĐây cũng sẽ là một năm đầy cảm xúc, và điều này có nghĩa là bạn sẽ trải nghiệm mọi cung bậc cảm xúc : tức giận, sợ hãi, buồn bã, vui vẻ, thất vọng... Tìm một lối thoát sáng tạo mà bạn có thể chuyển hướng nguồn cảm xúc đang dâng cao của mình. Khả năng sáng tạo và kỹ năng giao tiếp của bạn sẽ đạt đến đỉnh cao trong năm nay. \nĐây cũng là thời điểm định mệnh! Trong Năm 3, bạn có thể sẽ gặp một người có ảnh hưởng lớn đến cuộc sống của bạn hoặc mang lại cho bạn cơ hội thay đổi cuộc đời. \nNhững người có Năm Cá nhân này yêu thích sự tăng trưởng và mở rộng. Hãy thận trọng, đừng phóng đại và tô điểm quá nhiều. Bạn cũng cần chú ý đến việc tăng cân.";
const String nam_ca_nhan_4 =
    "Năm Cá nhân 4: Năm của kỷ luật & chi tiết\nNhiều cuốn sách Thần số học sẽ khiến bạn sợ hãi về yêu cầu sự chăm chỉ trong Năm Cá nhân 4. Hãy tập trung và tận tâm : điều này yêu cầu việc chú tâm vào chi tiết, hiểu về sự trì hoãn và tuân theo các quy tắc. Nếu phá vỡ các quy tắc, bạn sẽ phải gánh chịu hậu quả. Nếu tăng tốc, bạn sẽ đuổi kịp; nếu nói dối, bạn sẽ bị lộ. Hãy cẩn thận, đừng bỏ bê sức khỏe của mình. Hãy kiểm tra sức khỏe định kỳ.\nThông điệp của năm này là về sự buông bỏ và học cách tin tưởng vào cảm nhận thiên tính. Hãy tuân theo tự nhiên và đùng ép buộc thứ gì, nếu không chúng sẽ phản tác dụng, một cách tệ hại. ";
const String nam_ca_nhan_5 =
    "Năm cá nhân 5: Năm của sự thay đổi, tự do và đổi mới\nTrong năm cá nhân 5, bạn có thể bắt đầu cảm thấy bị giam cầm và sẵn sàng thay đổi. Đây là thời điểm giữa chu kì và bạn có thể cảm thấy 'ngứa ngáy', mong muốn điều gì đó mới mẻ. Năm nay, thường bạn sẽ muốn mua nhà mới, đổi xe, chuyển việc hoặc những thứ quan trọng khác. Năm 5 cũng là năm cho các mối quan hệ xã hội và là thời điểm tốt để bắt đầu một mối quan hệ yêu đường mới. Đây cũng là một năm tuyệt vời để đi du lịch, tham gia một cuộc phiêu lưu và trải nghiệm những điều mới. Hãy đặc biệt chú ý đến những người mới và những cơ hội mới đến với bạn. Hãy chú ý cẩn thận khi tham gia bàn tán và buôn chuyện trong năm nay - bạn sẽ thu hút họ như một thỏi nam châm! Bạn cũng có thể thấy mình hơi vụng về hoặc dễ gặp tai nạn.";
const String nam_ca_nhan_6 =
    "Năm cá nhân 6: Năm của gia đình và trách nhiệm\nNăm cá nhân của bạn kiểm soát quan hệ hôn nhân, việc sinh con hay liên quan đến cái chết, gia đình, nhà cửa và thậm chí cả vật nuôi của bạn. Bản chất ma quỷ/thiên thần của số 6 cũng áp dụng cho năm này.\nNăm 6 cũng kiểm soát việc học hành, vì vậy bạn có thể thấy mình quay trở lại trường học hoặc tham gia các lớp học hoặc hội thảo vào cuối tuần. Đây là một năm tuyệt vời để học điều gì đó mới. Từ tính cá nhân của bạn rất mạnh trong năm nay, vì vậy đây có thể là một năm thành công của mối quan hệ lãng mạn và chinh phục.\nBạn có thể thấy một vài điều tốt nhất và một vài sự kiện khó khăn về mặt cảm xúc trong cuộc đời bạn sẽ xảy ra trong năm 6. Bạn có thể kết hôn, và vài tháng sau, mất một người thân hoặc thú cưng.";
const String nam_ca_nhan_7 =
    "Năm Cá nhân 7 : Năm của chuyên môn & tự chăm sóc bản thân\nNăm này là thời điểm bạn trở thành chuyên gia ở lĩnh vực nào đó. Mài giữa các kỹ năng của bạn theo hướng chuyên môn hóa và thúc đẩy sự khám phá và tìm tòi. Đây là một năm tuyệt vời để làm điều gì đó tâm linh hoặc khám phá siêu hình học.\nĐây cũng là năm chăm sóc bản thân. Hãy dành thời gian cho chính mình. Hòa mình vào thiên nhiên hoặc tắm mình trong dòng nước sẽ tạo nên điều kỳ diệu cho tầm hồn bạn. Đây cũng là thời điểm tốt để bắt đầu thiền hoặc yoga. Bạn có thể sẽ cảm thấy mình thích ẩn mình ở một vài thời điểm trong năm này, thích ở nhà hơn là ra ngoài. Tuy nhiên, bạn phải đề phòng bệnh trầm cảm. Năm 7 sẽ buộc phải đánh giá cuộc sống và cảm xúc của mình.";
const String nam_ca_nhan_8 =
    "Năm Cá nhân 8: Năm thành đạt, quyền lực & tiền bạc \nNăm cá nhân 8 là về vòng quay tiền bạc. Bất cứ điều gì cũng có thể xảy ra trong năm nay - bạn có thể trúng xổ số hoặc phá sản.\nQuyền lực, dù tốt hay xấu, là điều mà bạn có thể đạt được trong năm này. Đây là một năm tuyệt vời để thăng tiến hoặc bắt đầu công việc kinh doanh của riêng bạn.\nBạn cũng nhận được nhiều phần thưởng và thành quả trong Năm 8. Đây là sự phản ánh trực tiếp những nỗ lực bạn đã bỏ ra trong suốt các năm từ 1 đên 8. Lợi ích vật chất, thành công, sự ổn định về tài chính và địa vị đều nằm trong tầm tay. Một lời cảnh báo nho nhỏ là Số 8 là con số cho thấy sự đảo ngược hoàn toàn, vì vậy, bạn có thể dễ dàng nhận thấy mình đang đi từ cao xuống thấp, thế nhưng thành quả đạt được tương xứng với những nỗ lực bạn đã bỏ ra trước đó.\nNếu bạn đã nghĩ về điều gì, hãy hành động ngay bây giờ. Ở năm 9, là qía muộn để bắt đầu những nỗ lực mới. Đây là cơ hội cuối cùng để bạn trở lại Năm 1.";
const String nam_ca_nhan_9 =
    "Năm Cá nhân 9: Năm hoàn thiện & giải phóng\nĐây là năm để hoàn thành mọi thứ và buông bỏ những điều không có ích với bạn. Bạn đã đạt đến cuối chu kỳ chín năm của mình và sẵn sàng nhận được phần thưởng từ tất cả sự phát triển và làm việc chăm chỉ của mình trước đó.\nNếu bạn cố gắng bắt đầu thứ gì đó trong Năm 9, như các mối quan hệ hoặc một công việc mới, chúng có thể sẽ không kéo dài. Lòng dũng cảm và sức mạnh của bạn sẽ chịu thử thách trong năm này. Các mối quan hệ độc hại sẽ biến mất và các vấn đề kéo dài có thể tìm ra cách giải quyết. Đây là thời gian để kết thúc và chữa lành.\nTha thứ là điều quan trọng lúc này. Hãy buông bỏ quá khứ để nhường chỗ cho tương lai phía trước. Bạn không muốn phải bực bội với vị khách không phải trả tiền phòng trong khi bạn có một khách thuê mới thú vị triển vọng trong Năm 1 tới đây. Hãy “dọn chỗ” cho những ước mơ lớn và lập kế hoạch.";
const String nam_ca_nhan_11 =
    "Năm Cá nhân 2 và 11/2 : Năm của các mối quan hệ và sự nhẫn nại \nNăm này là thời gian để nuôi dưỡng những hạt giống bạn đã gieo vào Năm 1. Thời gian của Paran bạn sẽ được sử dụng vào sử dụng tốt để chăm sóc những ý moo tưởng lớn mà bạn đã đề ra vào năm trước.\nBạn sẽ có những kết nối mạnh mẽ và gặp gỡ những người có thể giúp bạn đạt được mục tiêu và ước mơ của mình. Đây là thời điểm tuyệt vời cho những mối quan hệ lãng mạn và xây dựng gia đình.\nNăm này diễn biến chậm hơn một chút so với năm trước, và sự kiên nhẫn và khả năng thỏa hiệp của bạn sẽ được thử thách. Bạn cũng sẽ trải qua những việc liên quan đến sự nhạy cảm.\nNăm Vua 11 : Nếu hình dung 11 như hai số 1 đi cùng nhau (kết hôn, sinh con) hoặc tách rời nhau. (ly hôn, sự ra đi của một người thân yêu), bạn sẽ thấy năm này liên quan đến các sự kiện hoặc mối quan hệ định mệnh như thế nào. Bạn có trực giác nhạy bén, vì vậy hãy tin vào bản năng của mình.\nHãy lưu ý xem mình có đang bị lôi kéo, bướng. binh hay ích kỷ hay không, điều này bắt nguồn từ mức rung động thấp của năng lượng kép của hai số 1";
const String nam_ca_nhan_22 =
    "Năm Cá nhân 4 & 22/4 : Năm của kỷ luật & chi tiết\nNhiều cuốn sách Thần số học sẽ khiến bạn sợ hãi về yêu cầu sự chăm chỉ trong Năm Cá nhân 4. Hãy tập trung và tận tâm : điều này yêu cầu việc chú tâm vào chi tiết, hiểu về sự trì hoãn và tuân theo các quy tắc. Nếu phá vỡ các quy tắc, bạn sẽ phải gánh chịu hậu quả. Nếu tăng tốc, bạn sẽ đuổi kịp; nếu nói dối, bạn sẽ bị lộ. Hãy cẩn thận, đừng bỏ bê sức khỏe của mình. Hãy kiểm tra sức khỏe định kỳ.\nThông điệp của năm này là về sự buông bỏ và học cách tin tưởng vào cảm nhận thiên tính. Hãy tuân theo tự nhiên và đùng ép buộc thứ gì, nếu không chúng sẽ phản tác dụng, một cách tệ hại. \nNăm Vua 22 : Năm 4 là thời điểm bạn sắp xếp mọi thú theo thứ tự, tạo nền tảng để xây dựng ước mơ của mình. Bài học của bạn sẽ bao gồm việc kiểm soát cái tôi và học cách vượt qua những trở ngại mà bạn không thể kiểm soát. Điều quan trọng là bạn phải tin tưởng người khác như một phần trong kế hoạch tổng thể của mình.";

const String thai_do_1 =
    "Bạn là người độc đáo: Bạn mang dấu ấn cá nhân riêng của mình vào mọi việc bạn làm. Bạn có thể tỏ ra hung hăng nhưng đồng thời rất tự tin và có năng lực. Bạn tràn đầy nhiệt huyết và những ý tưởng tuyệt vời.\nBạn không sợ đối đầu, có thể rất bốc đồng và không phải lúc nào cũng xem xét hậu quả lâu dài của các hành động và quyết định của mình";
const String thai_do_2 =
    "Ấn tượng đầu tiên của người khác về bạn là một người tử tế, ngoại giao tốt và kiên nhẫn. Sự nhạy cảm đáng kinh nghạ của bạn thường được thể hiện dưới dạng những lo lắng. Hãy cẩn trọng về những gì bạn “nhận” từ người khác. Bạn không cần phải sở hữu những trải nghiệm, tâm trạng, ý kiến hoặc cảm xúc của người khác.";
const String thai_do_3 =
    "Bạn có vẻ ngoài vui vẻ và vô tư, nhưng rất nhạy cảm và thầm sợ chỉ trích và phản đối. Bạn có thể bị phân tán, thường kể nhiều câu chuyện cùng một lúc. Bạn thích cười và làm cho người khác cười. Bạn cực kỳ giỏi ngoại giao, thông minh và hóm hỉnh.\nBạn có vẻ khác thất thường và khó tính với bản thân. Đừng gò ép bản thân với đống cảm xúc hỗn loạn đó: Hãy vượt qua nó và đừng nhìn nhận mọi thứ một cách cá nhân thái quá.";
const String thai_do_4 =
    " Về mặt tình cảm, hãy cẩn thận với vẻ ngoài có vẻ bất cần hoặc lạnh lùng. Việc thể hiện sự dễ bị tổn thương về mặt cảm xúc không phải lúc nào cũng là điểm yếu. Bạn yêu thích các quy tắc, sự công bằng và mọi thứ phải công bằng. Bạn trân trọng việc người khác đánh giá cao kỹ năng tổ chức và quản lý của ban.";
const String thai_do_5 =
    "Bạn sử dụng sức hút của mình để điều hướng và đạt được những gì bạn muốn trong cuộc sống. Bạn thích một cuộc sống phiêu lưu, thú vị với nhịp sống nhanh, bạn dường như không sợ gì và luôn tìm kiếm sự nhanh chóng, đôi khi vội vàng. Bạn hoạt động tốt nhất trong môi trường luôn thay đổi, năng động và thậm chí hỗn loạn. Người khác sẽ chú ý đến việc bạn không thỏa hiệp với sự buồn chán.";
const String thai_do_6 =
    "Có năng lực, thông minh và nhanh trí, bạn rất giỏi trong trường hợp khẩn cấp và thậm chí còn giỏi hơn trong việc kiểm soát câu chuyện.  Như một bác sĩ giỏi, bạn biết phải làm gì và gọi cho ai. Những người khác nhìn nhận bạn là một người cầu toàn với gu thẩm mĩ tuyệt vời, luôn tìm cách đặt cái nhìn hoàn hảo của mình vào mọi thứ.";
const String thai_do_7 =
    "Bạn cảm thấy những câu chuyện phiếm có thể giết chết mình: Nếu việc trò chuyện bao gồm những tiếng cười giả tạo, bạn thà ở nhà. Điều này khiến bạn có vẻ lạc lõng và xa cách. Dường như có một bầu không khí bí ẩn về bạn vì bạn thích giữ chặt các lá bài của mình. Bạn muốn quan sát và đặt câu hỏi hơn là chia sẻ bất cứ việc gì quá riêng tư. \nHam học hỏi, bạn thích những cuộc trò chuyện có nội dung và riêng tư hơn là những cuộc trò chuyện vui vẻ theo nhóm. Những lời châm biếm và đôi khi là khiếu hài hước khô khan của bạn không phải lúc nào cũng được chấp nhận. Mọi người thấy bạn hấp dẫn nhưng khó nắm bắt. ";
const String thai_do_8 =
    "Sinh ra để dẫn đầu, và khi được cân bằng, không gì có thể ngăn cản sự phát triển của số này. Với khát khao được cống hiến, bạn có ước mơ, hoài bão lớn, điều này thường khiến bạn bị thất vọng. Bạn thể hiện sự tự tin và nỗ lực để duy trì một hình ảnh thành công.\nĐôi khi không khéo léo và cố chấp, bạn coi thường những thứ lãng phí thời gian. Suy cho cùng thì thời gian là tiền bạc, và nó có thể mang lại sự ổn định, an toàn và tự do mà bạn mong muốn. Nếu thấy mình thiếu nguồn lực hoặc thiếu khả năng kiểm soát, bạn có thể sẽ thể hiện thái độ chống đối và tức giận. Bạn sẽ nhanh chóng phải nhận Nghiệp, dù tốt hay xấu. ";
const String thai_do_9 =
    "Bạn có vẻ tự tin và sự quyến rũ để tận dụng. Mọi người thường có cảm giác bị đe dọa bởi bạn. Thái độ của số 9 có thể phân cực, mọi người sẽ yêu quý bạn hoặc coi thường bạn. Bất kỳ ai có điều gì đó muốn che giấu đều lo sợ bạn sẽ phơi bày chúng trong vô thức.";
const String thai_do_11 =
    "Ấn tượng đầu tiên của người khác về bạn là một người tử tế, ngoại giao tốt và kiên nhẫn. Sự nhạy cảm đáng kinh nghạ của bạn thường được thể hiện dưới dạng những lo lắng. Hãy cẩn trọng về những gì bạn “nhận” từ người khác. Bạn không cần phải sở hữu những trải nghiệm, tâm trạng, ý kiến hoặc cảm xúc của người khác.\nVới con số Vua 11, sẽ có thêm trực giạc mãnh liệt và thậm chí nhạy cảm hơn với những đặc điểm tính cách của số 2. Bạn ở trạng thái tốt nhất khi tuyền hứng cho người khác.";
const String thai_do_33 =
    "Có năng lực, thông minh và nhanh trí, bạn rất giỏi trong trường hợp khẩn cấp và thậm chí còn giỏi hơn trong việc kiểm soát câu chuyện.  Như một bác sĩ giỏi, bạn biết phải làm gì và gọi cho ai. Những người khác nhìn nhận bạn là một người cầu toàn với gu thẩm mĩ tuyệt vời, luôn tìm cách đặt cái nhìn hoàn hảo của mình vào mọi thứ.";
const String thai_do_22 =
    "Về mặt tình cảm, hãy cẩn thận với vẻ ngoài có vẻ bất cần hoặc lạnh lùng. Việc thể hiện sự dễ bị tổn thương về mặt cảm xúc không phải lúc nào cũng là điểm yếu. Bạn yêu thích các quy tắc, sự công bằng và mọi thứ phải công bằng. Bạn trân trọng việc người khác đánh giá cao kỹ năng tổ chức và quản lý của ban.\nCon số Vua 22 có năng lượng của số 4 và cũng được nâng cấp thành người kiến tạo tài ba của số 22. Những người khác sẽ thấy khả năng tuyệt vời cảu bạn trong việc xây dựng thứ gì đó có giá trị lâu dài. Kiểm soát cái tôi của bạn: Bạn có thể tỏ ra tự thu mình.";

const String truong_thanh_1 =
    "Bạn cần có sự độc lập và tính cá nhân mạnh mẽ hơn và phải nỗ lực nhiều hơn để được công nhận và đền đáp. Cân trọng để không trở thành kẻ bắt nạt và gây chiến.";
const String truong_thanh_2 =
    "Sự nhạy cảm cũng như sự khôn khéo và khả năng ngoại giao của bạn sẽ tăng lên. Bạn phù hợp với những công việc phía sau hậu trường,lựa chọn hướng dẫn nhẹ nhàng thay vì sử dụng vũ lực.";
const String truong_thanh_3 =
    "Bạn sẽ trở nên hòa đồng và hướng ngoại hơn. Khả năng giao tiếp của bạn sẽ được cải thiện cùng sự nổi tiếng và tiêm nǎng sáng tạo của bạn. Bạn Có thể vẽ tranh, viết lách hoặc diễn xuất.";
const String truong_thanh_4 =
    "Bạn sẽ thấy mình trở thành người có kế hoạch, thực tế và có tổ chức hơn. Tránh việc quá cứng nhắc, không linh hoạt và cố chấp. Hãy nhớ dành thời gian để tận hưởng niềm vui!";
const String truong_thanh_5 =
    "Du lịch, tự do và những sự kiện bất ngờ sẽ chi phối nửa sau cuộc đời bạn. Khả năng kể chuyện của bạn sẽ phát triển, và bạn sẽ trở nên độc đáo và thú vị hơn, dám chấp nhận rủi ro hơn. Hãy cẩn thận với việc phân tán năng lượng của bạn.";
const String truong_thanh_6 =
    "Gia đình, bạn bè và cộng đồng sẽ ngày càng quan tâm đến bạn. Bạn sẽ trưởng thành nhu một nhà hiền triết thông thái và có thể đưa ra lời khuyên cũng như sự an ủi cho những ai cần nó. Con số Trưởng thành này hứa hẹn một tuổi già an toàn. Đây thường là những người con chǎm sóc cha mẹ già.";
const String truong_thanh_7 =
    "Bạn phải đề phòng việc có nên ẩn dật. Bạn sẽ dành thời gian để đọc và tiếp tục rèn luyện bản thân trong khi đặt ra những câu hỏi lớn trong cuộc sống. Trực giác của bạn sẽ phát triển mạnh mẽ hơn cũng như khả năng hình thành các ý kiến về kết luận độc đáo của bạn cũng được tăng cường.";
const String truong_thanh_8 =
    "Bạn sẽ học cách tách khỏi thành công vật chất. Nhiều người với con số Trưởng thành này không bao giờ thực sự nghỉ hưu, và ngày càng bị sự tích lũy và lòng tham chi phối.\nBạn có thể đạt được thành công và sự độc lập về tài chính nếu kiểm soát được cái tôi của mình và tập trung vào các hành động nhân đạo để duy trì sự cân bằng.";
const String truong_thanh_9 =
    "Trí tuệ, khiếu hài hước và tấm lòng nhân đạo của bạn đều sẽ phát triển. Hoạt động tình nguyện và mối quan tâm đến nghệ thuật và văn hóa sẽ mang lại niềm vui cho bạn. Bạn sẽ cố gắng đóng góp những điều có giá trị lâu dài.";
const String truong_thanh_11 =
    "Số 11 sẽ có thêm những trải nghiệm trực giác và tâm linh đáng kinh ngạc khi già đi. Hãi tin và cảm nhận của bạn. Sựu nhạu cảm và khả năng phán đoán tính cách của bạn sẽ ngày càng sâu sắc. Bạn sẽ phân biệt dối xử rõ với những người mà bạn cho phép bước vào thế giới của mình và kết quả là những mối quan hệ lâu dài.";
const String truong_thanh_22 =
    "Với Con số Trưởng thành này, bạn sẽ có một nền tảng vững chắc, trực giác nhạy bén, sự tự tin mới hình thành và sức mạnh cá nhân sâu sắc. Những công cụ này sẽ giúp bạn biến nhiều ước mơ thành hiện thực và để lại di sản.";
const String truong_thanh_33 =
    "Bạn làm mọi việc với sự tận tâm. Bây giờ bạn có thể mang tầm nhìn của mình vào cuộc sống với lòng trắc ẩn, tập trung năng lượng cảm xúc của bạn vào mục tiêu cao hơn và phù hợp với những hiểu biết tâm linh.\nCon số Trưởng thành của bạn là một cái gì đó để nắm bắt và đáng mong đợi. Bạn đang hợp nhất Đường đời và Vận Mệnh của mình thành 1 tổng thể kinh nghiệm và trí tuệ tối thượng. Bây giờ bạn có thể tự tin định hướng cuộc sống của mình và cuối cùng là thực hiện ước mơ.";
